ALTER TABLE CWMS_COUNTY MODIFY COUNTY_NAME VARCHAR2(60);

DELETE FROM CWMS_COUNTY WHERE COUNTY_CODE = 2231;
DELETE FROM CWMS_COUNTY WHERE COUNTY_CODE = 12025;

update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Unknown State or State N/A' where COUNTY_CODE = 0;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Alabama' where COUNTY_CODE = 1000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Alaska' where COUNTY_CODE = 2000;
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(2168,'168',2.168, 'Denali');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(2201,'201',2.201, 'Prince of Wales-Outer Ketchikan Census Area');
update CWMS_COUNTY set COUNTY_NAME =  'Skagway-Hoonah-Angoon Census Area' where COUNTY_CODE = 2232;
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(2282,'282',2.282, 'Yakutat');
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Arizona' where COUNTY_CODE = 4000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Arkansas' where COUNTY_CODE = 5000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for California' where COUNTY_CODE = 6000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Colorado' where COUNTY_CODE = 8000;
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(8014,'014',8.014, 'Broomfield');
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Connecticut' where COUNTY_CODE = 9000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Delaware' where COUNTY_CODE = 10000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for District of Columbia' where COUNTY_CODE = 11000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Florida' where COUNTY_CODE = 12000;
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(12086,'086',12.086, 'Miami-Dade');
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Georgia' where COUNTY_CODE = 13000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Hawaii' where COUNTY_CODE = 15000;
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(15005,'005',15.005, 'Kalawao');
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Idaho' where COUNTY_CODE = 16000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Illinois' where COUNTY_CODE = 17000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Indiana' where COUNTY_CODE = 18000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Iowa' where COUNTY_CODE = 19000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Kansas' where COUNTY_CODE = 20000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Kentucky' where COUNTY_CODE = 21000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Louisiana' where COUNTY_CODE = 22000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Maine' where COUNTY_CODE = 23000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Maryland' where COUNTY_CODE = 24000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Massachusetts' where COUNTY_CODE = 25000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Michigan' where COUNTY_CODE = 26000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Minnesota' where COUNTY_CODE = 27000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Mississippi' where COUNTY_CODE = 28000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Missouri' where COUNTY_CODE = 29000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Montana' where COUNTY_CODE = 30000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Nebraska' where COUNTY_CODE = 31000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Nevada' where COUNTY_CODE = 32000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for New Hampshire' where COUNTY_CODE = 33000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for New Jersey' where COUNTY_CODE = 34000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for New Mexico' where COUNTY_CODE = 35000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for New York' where COUNTY_CODE = 36000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for North Carolina' where COUNTY_CODE = 37000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for North Dakota' where COUNTY_CODE = 38000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Ohio' where COUNTY_CODE = 39000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Oklahoma' where COUNTY_CODE = 40000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Oregon' where COUNTY_CODE = 41000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Pennsylvania' where COUNTY_CODE = 42000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Rhode Island' where COUNTY_CODE = 44000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for South Carolina' where COUNTY_CODE = 45000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for South Dakota' where COUNTY_CODE = 46000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Tennessee' where COUNTY_CODE = 47000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Texas' where COUNTY_CODE = 48000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Utah' where COUNTY_CODE = 49000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Vermont' where COUNTY_CODE = 50000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Virginia' where COUNTY_CODE = 51000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Washington' where COUNTY_CODE = 53000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for West Virginia' where COUNTY_CODE = 54000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Wisconsin' where COUNTY_CODE = 55000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Wyoming' where COUNTY_CODE = 56000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for American Samoa' where COUNTY_CODE = 60000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Guam' where COUNTY_CODE = 66000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Marshall Islands' where COUNTY_CODE = 68000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Northern Mariana Islands' where COUNTY_CODE = 69000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Puerto Rico' where COUNTY_CODE = 72000;
update CWMS_COUNTY set COUNTY_NAME =  'Unknown County or County N/A for Virgin Islands of the U.S.' where COUNTY_CODE = 78000;
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(80000,'000',80, 'Unknown County or County N/A for Alberta');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(81000,'000',81, 'Unknown County or County N/A for British Columbia');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(82000,'000',82, 'Unknown County or County N/A for Manitoba');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(83000,'000',83, 'Unknown County or County N/A for New Brunswick');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(84000,'000',84, 'Unknown County or County N/A for Newfoundland');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(85000,'000',85, 'Unknown County or County N/A for Nova Scotia');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(86000,'000',86, 'Unknown County or County N/A for Northwest Territories');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(87000,'000',87, 'Unknown County or County N/A for Nunavut');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(88000,'000',88, 'Unknown County or County N/A for Ontario');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(89000,'000',89, 'Unknown County or County N/A for Prince Edward Island');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(90000,'000',90, 'Unknown County or County N/A for Quebec');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(91000,'000',91, 'Unknown County or County N/A for Saskatchewan');
INSERT INTO CWMS_COUNTY(COUNTY_CODE,COUNTY_ID,STATE_CODE,COUNTY_NAME) VALUES(92000,'000',92, 'Unknown County or County N/A for Yukon');
COMMIT;