CREATE TABLE AT_CMA_ERROR_LOG
(
  ID                 NUMBER,
  MESSAGE            CLOB,
  ADDITIONAL_INFO    CLOB,
  DISPLAY_LOCATION   VARCHAR2(40 BYTE),
  ASSOCIATION_TYPE   VARCHAR2(40 BYTE),
  PAGE_ITEM_NAME     VARCHAR2(255 BYTE),
  ROW_NUM            NUMBER,
  IS_INTERNAL_ERROR  VARCHAR2(1 BYTE),
  APEX_ERROR_CODE    VARCHAR2(255 BYTE),
  ORA_SQLCODE        NUMBER,
  ORA_SQLERRM        CLOB,
  ERROR_BACKTRACE    CLOB,
  COMPONENT_TYPE     VARCHAR2(30 BYTE),
  COMPONENT_ID       INTEGER,
  COMPONENT_NAME     VARCHAR2(255 BYTE),
  APPLICATION_ID     NUMBER,
  APP_PAGE_ID        NUMBER,
  APP_USER           VARCHAR2(255 BYTE),
  BROWSER_LANGUAGE   VARCHAR2(255 BYTE),
  DATE_TIME          DATE,
  REGION_ID          NUMBER,
  COLUMN_ALIAS       VARCHAR2(255 BYTE)
)
LOB (MESSAGE) STORE AS (
  TABLESPACE  CWMS_20AT_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (ADDITIONAL_INFO) STORE AS (
  TABLESPACE  CWMS_20AT_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (ORA_SQLERRM) STORE AS (
  TABLESPACE  CWMS_20AT_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOB (ERROR_BACKTRACE) STORE AS (
  TABLESPACE  CWMS_20AT_DATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  NOCACHE
  LOGGING)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/
