CREATE TABLE CWMS_STATE_SP
(
   STATE_CODE   NUMBER (14) NOT NULL,
   OBJECTID     INTEGER NOT NULL,
   AREA         NUMBER (12, 3) NOT NULL,
   STATE_NAME   VARCHAR2 (25 BYTE) NOT NULL,
   STATE_FIPS   VARCHAR2 (2 BYTE) NOT NULL,
   SUB_REGION   VARCHAR2 (7 BYTE) NOT NULL,
   STATE_ABBR   VARCHAR2 (2 BYTE) NOT NULL,
   SHAPE        MDSYS.SDO_GEOMETRY
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE CWMS_20.CWMS_STATE_SP
 ADD CONSTRAINT CWMS_STATE_SP_U1
  UNIQUE (STATE_NAME)
  ENABLE VALIDATE;

