services:
  database:
    image: registry.hecdev.net/oracle/database:19.3.0-ee
    container_name: cwms-dev-db
    volumes:
      - cwms-dev-oracle:/opt/oracle/oradata:rw
    environment:
      - ORACLE_PDB=CWMSDEV
      - ORACLE_PWD=password
      - ORACLE_EDITION=enterprise
    ports:
      - "1521:1521"
  schema:
    build:
      context: ./schema
    container_name: cwms-dev-schema
    environment:
      - DB_HOST_PORT=cwms-dev-db:1521
      - DB_NAME=/CWMSDEV
      - CWMS_USER=s0hectest
      - SYS_PASSWORD=password
      - CWMS_PASSWORD=password
      - BUILDUSER_PASSWORD=password
      - OFFICE_ID=HQ
      - OFFICE_EROC=S0
      - INSTALLONCE=0
      - QUIET=0
    restart: unless-stopped
  cwms-data:
    build:
      context: cwmsdata
    depends_on:
      - database
    container_name: cwms-dev-data
    command:
      - "-st"
      - " -c '-vv --huc 05130101 05130102 05130103 --parameter_code 00060 00065'"
    environment:
      - DB_HOST_PORT=cwms-dev-db:1521
      - DB_NAME=/CWMSDEV
      - CWMS_USER=s0hectest
      - CWMS_PASSWORD=password
      - OFFICE_ID=HQ
      - OFFICE_EROC=S0
    restart: unless-stopped

volumes:
  cwms-dev-oracle:
