# NOTE: Expect issues at this time, this not commonly used directly and likely needs more updates.
services:
  database:
    image: gvenzl/oracle-free:23.6-full
    container_name: cwms-dev-db
    restart: always
    volumes:
      - cwms-dev-oracle:/opt/oracle/oradata:rw
    environment:
      - ORACLE_PASSWORD=password
    ports:
      - "1521:1521"
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -s sys/${ORACLE_PASSWORD}@localhost/FREEPDB1 as sysdba | grep -q '1'" ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  schema:
    build:
      context: .
    container_name: cwms-dev-schema
    environment:
      - DB_HOST_PORT=cwms-dev-db:1521
      - DB_NAME=/FREEPDB1
      - CWMS_USER=s0hectest
      - SYS_PASSWORD=password
      - CWMS_PASSWORD=password
      - BUILDUSER_PASSWORD=password
      - OFFICE_ID=HQ
      - OFFICE_EROC=S0
      # With installonce set to 0 the schema will be removed (equivalent to ant clean build) each time this runs.
      - INSTALLONCE=0
      - QUIET=0
volumes:
  cwms-dev-oracle:
