CREATE TABLE AT_DATA_DISSEM
(
  OFFICE_CODE         NUMBER,
  FILTER_TO_CORPSNET  VARCHAR2(1 BYTE)          NOT NULL,
  FILTER_TO_DMZ       VARCHAR2(1 BYTE)          NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX AT_DATA_DISSEM_PK ON AT_DATA_DISSEM
(OFFICE_CODE)
LOGGING
NOPARALLEL;

ALTER TABLE AT_DATA_DISSEM ADD (
  CONSTRAINT AT_DATA_DISSEM_C01
  CHECK ("FILTER_TO_CORPSNET"='T' OR "FILTER_TO_CORPSNET"='F')
  ENABLE VALIDATE,
  CONSTRAINT AT_DATA_DISSEM_C02
  CHECK ("FILTER_TO_DMZ"='T' OR "FILTER_TO_DMZ"='F')
  ENABLE VALIDATE,
  CONSTRAINT AT_DATA_DISSEM_PK
  PRIMARY KEY
  (OFFICE_CODE)
  USING INDEX AT_DATA_DISSEM_PK
  ENABLE VALIDATE);

ALTER TABLE AT_DATA_DISSEM ADD (
  CONSTRAINT AT_DATA_DISSEM_R01 
  FOREIGN KEY (OFFICE_CODE) 
  REFERENCES CWMS_OFFICE (OFFICE_CODE)
  ENABLE VALIDATE);
