-------------------
-- general setup --
-------------------
whenever sqlerror exit;
set define on
set verify off
set pages 100
set serveroutput on
define cwms_schema = 'CWMS_20'
define cwms_dba_schema = 'CWMS_DBA'
alter session set current_schema = &cwms_schema;
------------------------------------------------------------
-- spool to file that identifies the database in the name --
------------------------------------------------------------
var db_name varchar2(61)
begin
   select nvl(primary_db_unique_name, db_unique_name) into :db_name from v$database;
end;
/
whenever sqlerror continue;
declare
   l_count pls_integer;
   l_name  varchar2(30);
begin
   select count(*) into l_count from all_objects where object_name = 'CDB_PDBS';
   if l_count > 0 then
      select name
        into l_name
        from v$database;
      :db_name := l_name;
      begin
         select pdb_name
           into l_name
           from cdb_pdbs;
      exception
         when no_data_found then
            l_name := null;
      end;
      if l_name is not null then
         :db_name := :db_name||'-'||l_name;
      end if;
   end if;
end;
/
whenever sqlerror exit;
column db_name new_value db_name
select :db_name as db_name from dual;
define logfile=update_&db_name._18.1.6_to_18.1.7.log
prompt log file = &logfile
spool &logfile append;
-------------------
-- do the update --
-------------------
prompt ################################################################################
prompt VERIFYING EXPECTED VERSION
select systimestamp from dual;
@@./18_1_7/verify_db_version
prompt ################################################################################
prompt UPDATING OBJECTS
------------
-- TABLES --
------------
prompt ################################################################################
prompt Creating AT_TSV_2021 table
@@./18_1_7/create_at_tsv_2021
prompt ################################################################################
prompt Move rows from INF table to AT_TSV_2021 
@@./18_1_7/move_rows_to_2021

prompt ################################################################################
prompt Updating primary key sizes

DROP INDEX AT_CLOB_IDX1; 
ALTER TABLE AT_CLOB MODIFY(CLOB_CODE NUMBER(14));
ALTER TABLE AT_CLOB MODIFY(OFFICE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_CLOB_IDX1 ON AT_CLOB(OFFICE_CODE,UPPER("ID")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_CWMS_TS_ID MODIFY(INTERVAL NUMBER(14));
ALTER TABLE AT_DOCUMENT_TYPE MODIFY(DOCUMENT_TYPE_CODE NUMBER(14));
ALTER TABLE AT_EMBANK_PROTECTION_TYPE MODIFY(PROTECTION_TYPE_CODE NUMBER(14));
ALTER TABLE AT_EMBANK_STRUCTURE_TYPE MODIFY(STRUCTURE_TYPE_CODE NUMBER(14));
ALTER TABLE AT_ENTITY_LOCATION MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_ENTITY_LOCATION MODIFY(ENTITY_CODE NUMBER(14));
ALTER TABLE AT_FILE_EXTENSION MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_FORECAST_SPEC MODIFY(FORECAST_SPEC_CODE NUMBER(14));
ALTER TABLE AT_FORECAST_SPEC MODIFY(TARGET_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_FORECAST_SPEC MODIFY(SOURCE_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_FORECAST_TEXT MODIFY(FORECAST_SPEC_CODE NUMBER(14));
ALTER TABLE AT_FORECAST_TEXT MODIFY(CLOB_CODE NUMBER(14));
ALTER TABLE AT_GATE_CH_COMPUTATION_CODE MODIFY(DISCHARGE_COMP_CODE NUMBER(14));
ALTER TABLE AT_GATE_RELEASE_REASON_CODE MODIFY(RELEASE_REASON_CODE NUMBER(14));
ALTER TABLE AT_GEOGRAPHIC_LOCATION MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_GOES MODIFY(GAGE_CODE NUMBER(14));
DROP INDEX AT_LOCATION_URL_U1;
ALTER TABLE AT_LOCATION_URL MODIFY(LOCATION_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_LOCATION_URL_U1 ON AT_LOCATION_URL(LOCATION_CODE,UPPER("URL_ID")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_LOCK MODIFY(LOCK_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_LOCK MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_LOCKAGE MODIFY(LOCKAGE_CODE NUMBER(14));
ALTER TABLE AT_LOCKAGE MODIFY(LOCKAGE_LOCATION_CODE NUMBER(14));
DROP INDEX AT_LOC_GROUP_ASSIGNMENT_IDX1;
ALTER TABLE AT_LOC_GROUP_ASSIGNMENT MODIFY(OFFICE_CODE NUMBER(14));
CREATE INDEX AT_LOC_GROUP_ASSIGNMENT_IDX1 ON AT_LOC_GROUP_ASSIGNMENT(OFFICE_CODE,UPPER(LOC_ALIAS_ID)) TABLESPACE CWMS_20DATA;
DROP INDEX AT_LOC_LVL_INDICATOR_U1;
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(LEVEL_INDICATOR_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(SPECIFIED_LEVEL_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(DURATION_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(ATTR_PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(ATTR_PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(ATTR_DURATION_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR MODIFY(REF_SPECIFIED_LEVEL_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_LOC_LVL_INDICATOR_U1 ON AT_LOC_LVL_INDICATOR(LOCATION_CODE, SPECIFIED_LEVEL_CODE, PARAMETER_CODE, DURATION_CODE, LEVEL_INDICATOR_ID, &cwms_schema..CWMS_ROUNDING.ROUND_F("ATTR_VALUE",12), ATTR_PARAMETER_CODE, REF_SPECIFIED_LEVEL_CODE, REF_ATTR_VALUE) TABLESPACE CWMS_20DATA;
ALTER TABLE AT_LOC_LVL_INDICATOR_COND MODIFY(LEVEL_INDICATOR_CODE NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR_COND MODIFY(COMPARISON_UNIT NUMBER(14));
ALTER TABLE AT_LOC_LVL_INDICATOR_COND MODIFY(RATE_COMPARISON_UNIT NUMBER(14));
ALTER TABLE AT_OPERATIONAL_STATUS_CODE MODIFY(OPERATIONAL_STATUS_CODE NUMBER(14));
ALTER TABLE AT_OUTLET MODIFY(OUTLET_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_OUTLET MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_OUTLET_CHARACTERISTIC MODIFY(OUTLET_CHARACTERISTIC_CODE NUMBER(14));
ALTER TABLE AT_OUTLET_CHARACTERISTIC MODIFY(OPENING_PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_PHYSICAL_TRANSFER_TYPE MODIFY(PHYS_TRANS_TYPE_CODE NUMBER(14));
ALTER TABLE AT_PRJ_LCK_REVOKER_RIGHTS MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_PROJECT MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_PROJECT MODIFY(PUMP_BACK_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_PROJECT MODIFY(NEAR_GAGE_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_PROJECT_AGREEMENT MODIFY(PROJECT_AGREEMENT_LOC_CODE NUMBER(14));
ALTER TABLE AT_PROJECT_AGREEMENT MODIFY(PROJECT_AGREEMENT_DOC_CODE NUMBER(14));
ALTER TABLE AT_PROJECT_LOCK MODIFY(PROJECT_CODE NUMBER(14));
ALTER TABLE AT_PROJECT_PURPOSES MODIFY(PURPOSE_CODE NUMBER(14));
DROP INDEX AT_PROPERTIES_UK1;
ALTER TABLE AT_PROPERTIES MODIFY(OFFICE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_PROPERTIES_UK1 ON AT_PROPERTIES(OFFICE_CODE, UPPER("PROP_CATEGORY"), UPPER("PROP_ID")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_RATING MODIFY(RATING_CODE NUMBER(14));
ALTER TABLE AT_RATING MODIFY(RATING_SPEC_CODE NUMBER(14));
ALTER TABLE AT_RATING MODIFY(REF_RATING_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_ROUNDING MODIFY(RATING_SPEC_CODE NUMBER(14));
DROP INDEX AT_RATING_SPEC_U1;
ALTER TABLE AT_RATING_SPEC MODIFY(RATING_SPEC_CODE NUMBER(14));
ALTER TABLE AT_RATING_SPEC MODIFY(TEMPLATE_CODE NUMBER(14));
ALTER TABLE AT_RATING_SPEC MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_RATING_SPEC MODIFY(SOURCE_AGENCY_CODE NUMBER(14));
ALTER TABLE AT_RATING_SPEC MODIFY(IN_RANGE_RATING_METHOD NUMBER(14));
ALTER TABLE AT_RATING_SPEC MODIFY(OUT_RANGE_LOW_RATING_METHOD NUMBER(14));
ALTER TABLE AT_RATING_SPEC MODIFY(OUT_RANGE_HIGH_RATING_METHOD NUMBER(14));
CREATE UNIQUE INDEX AT_RATING_SPEC_U1 ON AT_RATING_SPEC(TEMPLATE_CODE, LOCATION_CODE, UPPER("VERSION")) TABLESPACE CWMS_20AT_DATA;
DROP INDEX AT_RATING_TEMPLATE_U1;
ALTER TABLE AT_RATING_TEMPLATE MODIFY(TEMPLATE_CODE NUMBER(14));
ALTER TABLE AT_RATING_TEMPLATE MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_RATING_TEMPLATE MODIFY(DEP_PARAMETER_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_RATING_TEMPLATE_U1 ON AT_RATING_TEMPLATE(OFFICE_CODE, UPPER("PARAMETERS_ID"), UPPER("VERSION")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_RATING_VALUE MODIFY(RATING_IND_PARAM_CODE NUMBER(14));
ALTER TABLE AT_RATING_VALUE MODIFY(DEP_RATING_IND_PARAM_CODE NUMBER(14));
ALTER TABLE AT_RATING_VALUE MODIFY(NOTE_CODE NUMBER(14));
ALTER TABLE AT_RATING_VALUE_NOTE MODIFY(NOTE_CODE NUMBER(14));
ALTER TABLE AT_RATING_VALUE_NOTE MODIFY(OFFICE_CODE NUMBER(14));
DROP INDEX AT_SPECIFIED_LEVEL_U1;
ALTER TABLE AT_SPECIFIED_LEVEL MODIFY(SPECIFIED_LEVEL_CODE NUMBER(14));
ALTER TABLE AT_SPECIFIED_LEVEL MODIFY(OFFICE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_SPECIFIED_LEVEL_U1 ON AT_SPECIFIED_LEVEL(OFFICE_CODE, UPPER("SPECIFIED_LEVEL_ID")) TABLESPACE CWMS_20AT_DATA;
DROP INDEX AT_STD_TEXT_U1;
ALTER TABLE AT_STD_TEXT MODIFY(STD_TEXT_CODE NUMBER(14));
ALTER TABLE AT_STD_TEXT MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_STD_TEXT MODIFY(CLOB_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_STD_TEXT_U1 ON AT_STD_TEXT(OFFICE_CODE, UPPER("STD_TEXT_ID")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_STREAM MODIFY(STREAM_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAM MODIFY(DIVERTING_STREAM_CODE NUMBER(14));
ALTER TABLE AT_STREAM MODIFY(RECEIVING_STREAM_CODE NUMBER(14));
ALTER TABLE AT_STREAM_LOCATION MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAM_LOCATION MODIFY(STREAM_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAM_REACH MODIFY(STREAM_REACH_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAM_REACH MODIFY(STREAM_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAM_REACH MODIFY(UPSTREAM_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAM_REACH MODIFY(DOWNSTREAM_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAM_REACH MODIFY(CONFIGURATION_CODE NUMBER(14));
ALTER TABLE AT_TRANSITIONAL_RATING MODIFY(TRANSITIONAL_RATING_CODE NUMBER(14));
ALTER TABLE AT_TRANSITIONAL_RATING MODIFY(RATING_SPEC_CODE NUMBER(14));
ALTER TABLE AT_TRANSITIONAL_RATING_SEL MODIFY(TRANSITIONAL_RATING_CODE NUMBER(14));
ALTER TABLE AT_TRANSITIONAL_RATING_SRC MODIFY(TRANSITIONAL_RATING_CODE NUMBER(14));
ALTER TABLE AT_TRANSITIONAL_RATING_SRC MODIFY(RATING_SPEC_CODE NUMBER(14));
ALTER TABLE AT_TSV_2002 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2002 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2003 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2003 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2004 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2004 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2005 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2005 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2006 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2006 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2007 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2007 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2008 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2008 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2009 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2009 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2010 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2010 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2011 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2011 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2012 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2012 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2013 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2013 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2014 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2014 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2015 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2015 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2016 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2016 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2017 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2017 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2018 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2018 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2019 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2019 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_2020 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_2020 MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_ARCHIVAL MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_ARCHIVAL MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_BINARY MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_BINARY MODIFY(BLOB_CODE NUMBER(14));
ALTER TABLE AT_TSV_INF_AND_BEYOND MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_INF_AND_BEYOND MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_TSV_STD_TEXT MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_STD_TEXT MODIFY(STD_TEXT_CODE NUMBER(14));
ALTER TABLE AT_TSV_TEXT MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV_TEXT MODIFY(CLOB_CODE NUMBER(14));
ALTER TABLE AT_TS_DELETED_TIMES MODIFY(TS_CODE NUMBER(14));
DROP INDEX AT_TS_GROUP_ASSIGNMENT_IDX1;
ALTER TABLE AT_TS_GROUP_ASSIGNMENT MODIFY(OFFICE_CODE NUMBER(14));
CREATE INDEX AT_TS_GROUP_ASSIGNMENT_IDX1 ON AT_TS_GROUP_ASSIGNMENT(OFFICE_CODE, UPPER("TS_ALIAS_ID")) TABLESPACE CWMS_20DATA;
ALTER TABLE AT_TS_MSG_ARCHIVE_1 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TS_MSG_ARCHIVE_2 MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE MODIFY(KEY_PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE MODIFY(REFERENCE_TS_CODE NUMBER(14));
DROP INDEX AT_TS_PROFILE_INSTANCE_PK;
ALTER TABLE AT_TS_PROFILE_INSTANCE MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_INSTANCE MODIFY(KEY_PARAMETER_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_TS_PROFILE_INSTANCE_PK ON AT_TS_PROFILE_INSTANCE(LOCATION_CODE, KEY_PARAMETER_CODE, UPPER("VERSION_ID"), FIRST_DATE_TIME, VERSION_DATE) TABLESPACE CWMS_20DATA;
ALTER TABLE AT_TS_PROFILE_PARAM MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARAM MODIFY(KEY_PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARAM MODIFY(PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARSER MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARSER MODIFY(KEY_PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARSER MODIFY(TIME_ZONE_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARSER_PARAM MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARSER_PARAM MODIFY(KEY_PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARSER_PARAM MODIFY(PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_TS_PROFILE_PARSER_PARAM MODIFY(PARAMETER_UNIT NUMBER(14));
ALTER TABLE AT_TURBINE MODIFY(TURBINE_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TURBINE MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_CHARACTERISTIC MODIFY(TURBINE_CHARACTERISTIC_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_COMPUTATION_CODE MODIFY(TURBINE_COMP_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_SETTING_REASON MODIFY(TURB_SET_REASON_CODE NUMBER(14));
ALTER TABLE AT_UNIT_ALIAS MODIFY(UNIT_CODE NUMBER(14));
ALTER TABLE AT_VERT_DATUM_LOCAL MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_VIRTUAL_RATING MODIFY(VIRTUAL_RATING_CODE NUMBER(14));
ALTER TABLE AT_VIRTUAL_RATING MODIFY(RATING_SPEC_CODE NUMBER(14));
ALTER TABLE AT_VIRTUAL_RATING_ELEMENT MODIFY(VIRTUAL_RATING_ELEMENT_CODE NUMBER(14));
ALTER TABLE AT_VIRTUAL_RATING_ELEMENT MODIFY(VIRTUAL_RATING_CODE NUMBER(14));
ALTER TABLE AT_VIRTUAL_RATING_ELEMENT MODIFY(RATING_SPEC_CODE NUMBER(14));
ALTER TABLE AT_VIRTUAL_RATING_UNIT MODIFY(VIRTUAL_RATING_ELEMENT_CODE NUMBER(14));
ALTER TABLE AT_VIRTUAL_RATING_UNIT MODIFY(UNIT_CODE NUMBER(14));
DROP INDEX AT_WATER_USER_IDX1;
ALTER TABLE AT_WATER_USER MODIFY(WATER_USER_CODE NUMBER(14));
ALTER TABLE AT_WATER_USER MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_WATER_USER_IDX1 ON AT_WATER_USER(PROJECT_LOCATION_CODE, UPPER("ENTITY_NAME")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_WS_CONTRACT_TYPE MODIFY(WS_CONTRACT_TYPE_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DATASTORE_DSS MODIFY(DATASTORE_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DATASTORE_DSS MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_XREF_WAT_USR_CONTRACT_DOCS MODIFY(WATER_USER_CONTRACT_DOC_CODE NUMBER(14));
ALTER TABLE AT_XREF_WAT_USR_CONTRACT_DOCS MODIFY(DOCUMENT_CODE NUMBER(14));
ALTER TABLE AT_XREF_WAT_USR_CONTRACT_DOCS MODIFY(WATER_USER_CONTRACT_CODE NUMBER(14));
ALTER TABLE CWMS_ABSTRACT_PARAMETER MODIFY(ABSTRACT_PARAM_CODE NUMBER(14));
ALTER TABLE CWMS_BASE_PARAMETER MODIFY(BASE_PARAMETER_CODE NUMBER(14));
ALTER TABLE CWMS_BASE_PARAMETER MODIFY(ABSTRACT_PARAM_CODE NUMBER(14));
ALTER TABLE CWMS_BASE_PARAMETER MODIFY(UNIT_CODE NUMBER(14));
ALTER TABLE CWMS_BASE_PARAMETER MODIFY(DISPLAY_UNIT_CODE_SI NUMBER(14));
ALTER TABLE CWMS_BASE_PARAMETER MODIFY(DISPLAY_UNIT_CODE_EN NUMBER(14));
ALTER TABLE CWMS_COUNTY MODIFY(COUNTY_CODE NUMBER(14));
ALTER TABLE CWMS_COUNTY MODIFY(STATE_CODE NUMBER(14));
ALTER TABLE CWMS_COUNTY_SP MODIFY(COUNTY_CODE NUMBER(14));
ALTER TABLE CWMS_DSS_PARAMETER_TYPE MODIFY(DSS_PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE CWMS_DSS_PARAMETER_TYPE MODIFY(PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE CWMS_DURATION MODIFY(DURATION_CODE NUMBER(14));
ALTER TABLE CWMS_DURATION MODIFY(DURATION NUMBER(14));
ALTER TABLE CWMS_GAGE_METHOD MODIFY(METHOD_CODE NUMBER(14));
ALTER TABLE CWMS_GAGE_TYPE MODIFY(GAGE_TYPE_CODE NUMBER(14));
ALTER TABLE CWMS_GAGE_TYPE MODIFY(INQUIRY_METHOD NUMBER(14));
ALTER TABLE CWMS_GAGE_TYPE MODIFY(TRANSMIT_METHOD NUMBER(14));
ALTER TABLE CWMS_GATE_TYPE MODIFY(GATE_TYPE_CODE NUMBER(14));
ALTER TABLE CWMS_INTERVAL MODIFY(INTERVAL_CODE NUMBER(14));
ALTER TABLE CWMS_INTERVAL MODIFY(INTERVAL NUMBER(14));
ALTER TABLE CWMS_INTERVAL_OFFSET MODIFY(INTERVAL_OFFSET_CODE NUMBER(14));
ALTER TABLE CWMS_INTERVAL_OFFSET MODIFY(INTERVAL_OFFSET_VALUE NUMBER(14));
ALTER TABLE CWMS_LOCATION_KIND MODIFY(LOCATION_KIND_CODE NUMBER(14));
ALTER TABLE CWMS_LOCATION_KIND MODIFY(PARENT_LOCATION_KIND NUMBER(14));
ALTER TABLE CWMS_NATION_SP MODIFY(POP_CNTRY NUMBER(14));
ALTER TABLE CWMS_OFFICE MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE CWMS_OFFICE MODIFY(REPORT_TO_OFFICE_CODE NUMBER(14));
ALTER TABLE CWMS_OFFICE MODIFY(DB_HOST_OFFICE_CODE NUMBER(14));
ALTER TABLE CWMS_PARAMETER_TYPE MODIFY(PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE CWMS_RATING_METHOD MODIFY(RATING_METHOD_CODE NUMBER(14));
ALTER TABLE CWMS_STATE MODIFY(STATE_CODE NUMBER(14));
ALTER TABLE CWMS_STATE_SP MODIFY(STATE_CODE NUMBER(14));
ALTER TABLE CWMS_TIME_ZONE MODIFY(TIME_ZONE_CODE NUMBER(14));
ALTER TABLE CWMS_TZ_USAGE MODIFY(TZ_USAGE_CODE NUMBER(14));
ALTER TABLE CWMS_UNIT MODIFY(UNIT_CODE NUMBER(14));
ALTER TABLE CWMS_UNIT MODIFY(ABSTRACT_PARAM_CODE NUMBER(14));
ALTER TABLE CWMS_UNIT_CONVERSION MODIFY(ABSTRACT_PARAM_CODE NUMBER(14));
ALTER TABLE CWMS_UNIT_CONVERSION MODIFY(FROM_UNIT_CODE NUMBER(14));
ALTER TABLE CWMS_UNIT_CONVERSION MODIFY(TO_UNIT_CODE NUMBER(14));
ALTER TABLE CWMS_USACE_DAM MODIFY(MAX_DISCHARGE NUMBER(14,3));
ALTER TABLE CWMS_USACE_DAM MODIFY(DRAINAGE_AREA NUMBER(14,3));
ALTER TABLE CWMS_VERTCON_HEADER MODIFY(DATASET_CODE NUMBER(14));
ALTER TABLE CWMS_VERTCON_HEADER MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_BASIN MODIFY(BASIN_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_BASIN MODIFY(PRIMARY_STREAM_CODE NUMBER(14));
ALTER TABLE AT_BASIN MODIFY(PARENT_BASIN_CODE NUMBER(14));
DROP INDEX AT_BLOB_U1;
ALTER TABLE AT_BLOB MODIFY(BLOB_CODE NUMBER(14));
ALTER TABLE AT_BLOB MODIFY(OFFICE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_BLOB_U1 ON AT_BLOB(OFFICE_CODE, UPPER("ID")) TABLESPACE CWMS_20AT_DATA;
DROP INDEX AT_COMP_OUTLET_IDX1;
ALTER TABLE AT_COMP_OUTLET MODIFY(COMPOUND_OUTLET_CODE NUMBER(14));
ALTER TABLE AT_COMP_OUTLET MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_COMP_OUTLET_IDX1 ON AT_COMP_OUTLET(PROJECT_LOCATION_CODE, UPPER("COMPOUND_OUTLET_ID")) TABLESPACE CWMS_20DATA;
DROP INDEX AT_COMP_OUTLET_CONN_IDX1;
ALTER TABLE AT_COMP_OUTLET_CONN MODIFY(AT_COMP_OUTLET_CONN_CODE NUMBER(14));
ALTER TABLE AT_COMP_OUTLET_CONN MODIFY(COMPOUND_OUTLET_CODE NUMBER(14));
ALTER TABLE AT_COMP_OUTLET_CONN MODIFY(OUTLET_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_COMP_OUTLET_CONN MODIFY(NEXT_OUTLET_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_COMP_OUTLET_CONN_IDX1 ON AT_COMP_OUTLET_CONN(COMPOUND_OUTLET_CODE, OUTLET_LOCATION_CODE, NVL("NEXT_OUTLET_CODE",0)) TABLESPACE CWMS_20DATA;
DROP INDEX AT_CONFIGURATION_IDX_ID;
ALTER TABLE AT_CONFIGURATION MODIFY(CONFIGURATION_CODE NUMBER(14));
ALTER TABLE AT_CONFIGURATION MODIFY(PARENT_CODE NUMBER(14));
ALTER TABLE AT_CONFIGURATION MODIFY(OFFICE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_CONFIGURATION_IDX_ID ON AT_CONFIGURATION(OFFICE_CODE, UPPER("CONFIGURATION_ID")) TABLESPACE CWMS_20DATA;
ALTER TABLE AT_DISPLAY_SCALE MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_DISPLAY_SCALE MODIFY(PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_DISPLAY_SCALE MODIFY(UNIT_CODE NUMBER(14));
ALTER TABLE AT_DOCUMENT MODIFY(DOCUMENT_CODE NUMBER(14));
ALTER TABLE AT_DOCUMENT MODIFY(DOCUMENT_TYPE_CODE NUMBER(14));
ALTER TABLE AT_DOCUMENT MODIFY(DOCUMENT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_DOCUMENT MODIFY(DOCUMENT_PREVIEW_CODE NUMBER(14));
ALTER TABLE AT_DOCUMENT MODIFY(STORED_DOCUMENT NUMBER(14));
ALTER TABLE AT_EMBANKMENT MODIFY(EMBANKMENT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_EMBANKMENT MODIFY(EMBANKMENT_PROJECT_LOC_CODE NUMBER(14));
ALTER TABLE AT_EMBANKMENT MODIFY(STRUCTURE_TYPE_CODE NUMBER(14));
ALTER TABLE AT_EMBANKMENT MODIFY(UPSTREAM_PROT_TYPE_CODE NUMBER(14));
ALTER TABLE AT_EMBANKMENT MODIFY(DOWNSTREAM_PROT_TYPE_CODE NUMBER(14));
DROP INDEX AT_ENTITY_IDX_ID;
ALTER TABLE AT_ENTITY MODIFY(ENTITY_CODE NUMBER(14));
ALTER TABLE AT_ENTITY MODIFY(PARENT_CODE NUMBER(14));
ALTER TABLE AT_ENTITY MODIFY(OFFICE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_ENTITY_IDX_ID ON AT_ENTITY(OFFICE_CODE, UPPER("ENTITY_ID")) TABLESPACE CWMS_20DATA;
DROP INDEX AT_GAGE_IDX1;
ALTER TABLE AT_GAGE MODIFY(GAGE_CODE NUMBER(14));
ALTER TABLE AT_GAGE MODIFY(GAGE_TYPE_CODE NUMBER(14));
ALTER TABLE AT_GAGE MODIFY(GAGE_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_GAGE MODIFY(ASSOCIATED_LOCATION_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_GAGE_IDX1 ON AT_GAGE(GAGE_LOCATION_CODE, UPPER("GAGE_ID")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_GAGE_SENSOR MODIFY(GAGE_CODE NUMBER(14));
ALTER TABLE AT_GAGE_SENSOR MODIFY(PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_GAGE_SENSOR MODIFY(UNIT_CODE NUMBER(14));
ALTER TABLE AT_GATE_CHANGE MODIFY(GATE_CHANGE_CODE NUMBER(14));
ALTER TABLE AT_GATE_CHANGE MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_GATE_CHANGE MODIFY(DISCHARGE_COMPUTATION_CODE NUMBER(14));
ALTER TABLE AT_GATE_CHANGE MODIFY(RELEASE_REASON_CODE NUMBER(14));
ALTER TABLE AT_GATE_GROUP MODIFY(LOC_GROUP_CODE NUMBER(14));
ALTER TABLE AT_GATE_GROUP MODIFY(GATE_TYPE_CODE NUMBER(14));
ALTER TABLE AT_GATE_SETTING MODIFY(GATE_SETTING_CODE NUMBER(14));
ALTER TABLE AT_GATE_SETTING MODIFY(GATE_CHANGE_CODE NUMBER(14));
ALTER TABLE AT_GATE_SETTING MODIFY(OUTLET_LOCATION_CODE NUMBER(14));
DROP INDEX AT_LOCATION_LEVEL_U1;
ALTER TABLE AT_LOCATION_LEVEL MODIFY(LOCATION_LEVEL_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(SPECIFIED_LEVEL_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(DURATION_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(ATTRIBUTE_PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(ATTRIBUTE_PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(ATTRIBUTE_DURATION_CODE NUMBER(14));
ALTER TABLE AT_LOCATION_LEVEL MODIFY(TS_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_LOCATION_LEVEL_U1 ON AT_LOCATION_LEVEL(LOCATION_CODE, SPECIFIED_LEVEL_CODE, PARAMETER_CODE, PARAMETER_TYPE_CODE, DURATION_CODE, LOCATION_LEVEL_DATE, NVL("ATTRIBUTE_PARAMETER_CODE",(-1)), NVL("ATTRIBUTE_PARAMETER_TYPE_CODE",(-1)), NVL("ATTRIBUTE_DURATION_CODE",(-1)), NVL("ATTRIBUTE_VALUE",(-1))) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_LOG_MESSAGE MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_OVERFLOW MODIFY(OVERFLOW_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_OVERFLOW MODIFY(RATING_SPEC_CODE NUMBER(14));
DROP INDEX AT_PHYSICAL_LOCATION_U1;
ALTER TABLE AT_PHYSICAL_LOCATION MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_PHYSICAL_LOCATION MODIFY(BASE_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_PHYSICAL_LOCATION MODIFY(TIME_ZONE_CODE NUMBER(14));
ALTER TABLE AT_PHYSICAL_LOCATION MODIFY(COUNTY_CODE NUMBER(14));
ALTER TABLE AT_PHYSICAL_LOCATION MODIFY(LOCATION_KIND NUMBER(14));
ALTER TABLE AT_PHYSICAL_LOCATION MODIFY(OFFICE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_PHYSICAL_LOCATION_U1 ON AT_PHYSICAL_LOCATION(BASE_LOCATION_CODE, UPPER("SUB_LOCATION_ID")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_PROJECT_CONGRESS_DISTRICT MODIFY(PROJECT_CONGRESS_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_PROJECT_CONGRESS_DISTRICT MODIFY(PROJECT_CONGRESS_STATE_CODE NUMBER(14));
ALTER TABLE AT_PROJECT_CONGRESS_DISTRICT MODIFY(CONGRESSIONAL_DISTRICT NUMBER(14));
ALTER TABLE AT_PROJECT_PURPOSE MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_PROJECT_PURPOSE MODIFY(PROJECT_PURPOSE_CODE NUMBER(14));
ALTER TABLE AT_PUMP MODIFY(PUMP_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAM_SPEC MODIFY(IND_PARAM_SPEC_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAM_SPEC MODIFY(TEMPLATE_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAM_SPEC MODIFY(PARAMETER_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAM_SPEC MODIFY(IN_RANGE_RATING_METHOD NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAM_SPEC MODIFY(OUT_RANGE_LOW_RATING_METHOD NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAM_SPEC MODIFY(OUT_RANGE_HIGH_RATING_METHOD NUMBER(14));
ALTER TABLE AT_SEASONAL_LOCATION_LEVEL MODIFY(LOCATION_LEVEL_CODE NUMBER(14));
ALTER TABLE AT_STREAMFLOW_MEAS MODIFY(LOCATION_CODE NUMBER(14));
ALTER TABLE AT_STREAMFLOW_MEAS MODIFY(AGENCY_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_CHANGE MODIFY(TURBINE_CHANGE_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_CHANGE MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_CHANGE MODIFY(TURBINE_SETTING_REASON_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_CHANGE MODIFY(TURBINE_DISCHARGE_COMP_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_SETTING MODIFY(TURBINE_SETTING_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_SETTING MODIFY(TURBINE_CHANGE_CODE NUMBER(14));
ALTER TABLE AT_TURBINE_SETTING MODIFY(TURBINE_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_VERT_DATUM_OFFSET MODIFY(LOCATION_CODE NUMBER(14));
DROP INDEX AT_WATER_USER_CONTRACT_IDX1;
ALTER TABLE AT_WATER_USER_CONTRACT MODIFY(WATER_USER_CONTRACT_CODE NUMBER(14));
ALTER TABLE AT_WATER_USER_CONTRACT MODIFY(WATER_USER_CODE NUMBER(14));
ALTER TABLE AT_WATER_USER_CONTRACT MODIFY(WATER_SUPPLY_CONTRACT_TYPE NUMBER(14));
ALTER TABLE AT_WATER_USER_CONTRACT MODIFY(PUMP_OUT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_WATER_USER_CONTRACT MODIFY(PUMP_OUT_BELOW_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_WATER_USER_CONTRACT MODIFY(PUMP_IN_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_WATER_USER_CONTRACT MODIFY(STORAGE_UNIT_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_WATER_USER_CONTRACT_IDX1 ON AT_WATER_USER_CONTRACT(WATER_USER_CODE, UPPER("CONTRACT_NAME")) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_WAT_USR_CONTRACT_ACCOUNTING MODIFY(WAT_USR_CONTRACT_ACCT_CODE NUMBER(14));
ALTER TABLE AT_WAT_USR_CONTRACT_ACCOUNTING MODIFY(WATER_USER_CONTRACT_CODE NUMBER(14));
ALTER TABLE AT_WAT_USR_CONTRACT_ACCOUNTING MODIFY(PUMP_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_WAT_USR_CONTRACT_ACCOUNTING MODIFY(PHYS_TRANS_TYPE_CODE NUMBER(14));
ALTER TABLE AT_XCHG_SET MODIFY(XCHG_SET_CODE NUMBER(14));
ALTER TABLE AT_XCHG_SET MODIFY(DATASTORE_CODE NUMBER(14));
ALTER TABLE AT_XCHG_SET MODIFY(OFFICE_CODE NUMBER(14));
ALTER TABLE AT_XCHG_SET MODIFY(INTERPOLATE_COUNT NUMBER(14));
ALTER TABLE CWMS_DATA_QUALITY MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE CWMS_VERTCON_DATA MODIFY(DATASET_CODE NUMBER(14));
DROP INDEX AT_CONSTRUCTION_HIST_IDX_1;
ALTER TABLE AT_CONSTRUCTION_HISTORY MODIFY(CONSTRUCTION_HISTORY_CODE NUMBER(14));
ALTER TABLE AT_CONSTRUCTION_HISTORY MODIFY(PROJECT_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_CONSTRUCTION_HISTORY MODIFY(CONSTRUCTION_LOCATION_CODE NUMBER(14));
ALTER TABLE AT_CONSTRUCTION_HISTORY MODIFY(OPERATIONAL_STATUS_CODE NUMBER(14));
ALTER TABLE AT_CONSTRUCTION_HISTORY MODIFY(CONSTRUCTION_HISTORY_DOC_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_CONSTRUCTION_HIST_IDX_1 ON AT_CONSTRUCTION_HISTORY(PROJECT_LOCATION_CODE, CONSTRUCTION_LOCATION_CODE, UPPER("CONSTRUCTION_ID")) TABLESPACE CWMS_20AT_DATA;
DROP INDEX AT_CWMS_TS_SPEC_UI;
ALTER TABLE AT_CWMS_TS_SPEC MODIFY(PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE AT_CWMS_TS_SPEC MODIFY(INTERVAL_CODE NUMBER(14));
ALTER TABLE AT_CWMS_TS_SPEC MODIFY(DURATION_CODE NUMBER(14));
ALTER TABLE AT_CWMS_TS_SPEC MODIFY(TIME_ZONE_CODE NUMBER(14));
CREATE UNIQUE INDEX AT_CWMS_TS_SPEC_UI ON AT_CWMS_TS_SPEC(LOCATION_CODE, PARAMETER_TYPE_CODE, PARAMETER_CODE, INTERVAL_CODE, DURATION_CODE, UPPER("VERSION"), DELETE_DATE) TABLESPACE CWMS_20AT_DATA;
ALTER TABLE AT_FORECAST_TS MODIFY(FORECAST_SPEC_CODE NUMBER(14));
ALTER TABLE AT_FORECAST_TS MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAMETER MODIFY(RATING_IND_PARAM_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAMETER MODIFY(RATING_CODE NUMBER(14));
ALTER TABLE AT_RATING_IND_PARAMETER MODIFY(IND_PARAM_SPEC_CODE NUMBER(14));
ALTER TABLE AT_TSV MODIFY(TS_CODE NUMBER(14));
ALTER TABLE AT_TSV MODIFY(QUALITY_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS MODIFY(MAPPING_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS MODIFY(XCHG_SET_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS MODIFY(CWMS_TS_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS MODIFY(DSS_PARAMETER_TYPE_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS MODIFY(TIME_ZONE_CODE NUMBER(14));
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS MODIFY(TZ_USAGE_CODE NUMBER(14));
ALTER TABLE AT_RATING_EXTENSION_VALUE MODIFY(RATING_IND_PARAM_CODE NUMBER(14));
ALTER TABLE AT_RATING_EXTENSION_VALUE MODIFY(DEP_RATING_IND_PARAM_CODE NUMBER(14));
ALTER TABLE AT_RATING_EXTENSION_VALUE MODIFY(NOTE_CODE NUMBER(14));


--------------
-- PACKAGES --
--------------
@../cwms/cwms_alarm_pkg_body
@../cwms/cwms_apex_pkg_body
@../cwms/cwms_cat_pkg
@../cwms/cwms_cat_pkg_body
@../cwms/cwms_basin_pkg_body
@../cwms/cwms_display_pkg_body
@../cwms/cwms_embank_pkg_body
@../cwms/cwms_forecast_pkg_body
@../cwms/cwms_gage_pkg_body
@../cwms/cwms_level_pkg_body
@../cwms/cwms_loc_pkg_body
@../cwms/cwms_lock_pkg_body
@../cwms/cwms_msg_pkg
@../cwms/cwms_msg_pkg_body
@../cwms/cwms_outlet_pkg_body
@../cwms/cwms_project_pkg_body
@../cwms/cwms_prop_pkg_body
@../cwms/cwms_rating_pkg_body
@../cwms/cwms_stream_pkg_body
@../cwms/cwms_text_pkg_body
@../cwms/cwms_ts_pkg_body
@../cwms/cwms_turbine_pkg_body
@../cwms/cwms_usgs_pkg_body
@../cwms/cwms_util_pkg_body
@../cwms/cwms_water_supply_pkg_body
@../cwms/cwms_xchg_pkg_body

-----------
-- TYPES --
-----------

drop type cat_dss_file_obj_t force;
@../cwms/types/cat_dss_file_obj_t
drop type cat_ts_cwms_20_obj_t force;
@../cwms/types/cat_ts_cwms_20_obj_t
drop type loc_lvl_indicator_cond_t force;
@../cwms/types/loc_lvl_indicator_cond_t
drop type zloc_lvl_indicator_t force;
@../cwms/types/zloc_lvl_indicator_t
drop type zlocation_level_t force;
@../cwms/types/zlocation_level_t
drop type location_ref_t force;
@../cwms/types/location_ref_t
@../cwms/types/location_ref_t-body
drop type zlocation_level_t force;
@../cwms/types/zlocation_level_t
@../cwms/types/zlocation_level_t-body
drop type location_level_t force;
@../cwms/types/location_level_t
@../cwms/types/location_level_t-body
drop type loc_lvl_indicator_cond_t force;
@../cwms/types/loc_lvl_indicator_cond_t
@../cwms/types/loc_lvl_indicator_cond_t-body
drop type rating_ind_parameter_t force;
@../cwms/types/rating_ind_parameter_t
@../cwms/types/rating_ind_parameter_t-body
drop type rating_ind_param_spec_t force;
@../cwms/types/rating_ind_param_spec_t
@../cwms/types/rating_ind_param_spec_t-body
drop type rating_t force;
@../cwms/types/rating_t
@../cwms/types/rating_t-body
drop type rating_template_t force;
@../cwms/types/rating_template_t
@../cwms/types/rating_template_t-body
drop type rating_spec_t force;
@../cwms/types/rating_spec_t
@../cwms/types/rating_spec_t-body
drop type rating_value_t force;
@../cwms/types/rating_value_t
@../cwms/types/rating_value_t-body
drop type stream_rating_t force;
@../cwms/types/stream_rating_t
@../cwms/types/stream_rating_t-body
drop type zloc_lvl_indicator_t force;
@../cwms/types/zloc_lvl_indicator_t
@../cwms/types/zloc_lvl_indicator_t-body

-- Restore grants

GRANT EXECUTE ON CWMS_20.ZLOC_LVL_INDICATOR_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.ZLOCATION_LEVEL_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.STREAM_RATING_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.RATING_VALUE_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.RATING_TEMPLATE_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.RATING_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.RATING_SPEC_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.RATING_IND_PARAM_SPEC_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.RATING_IND_PARAMETER_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.LOC_LVL_INDICATOR_COND_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.LOCATION_REF_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.LOCATION_LEVEL_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.CAT_TS_CWMS_20_OBJ_T TO CWMS_USER;
GRANT EXECUTE ON CWMS_20.CAT_DSS_FILE_OBJ_T TO CWMS_USER;

-----------
-- VIEWS --
-----------

@18_1_7/at_comp_outlet_conn_tr1.sql


prompt ################################################################################
prompt INVALID OBJECTS...
select systimestamp from dual;
set pagesize 100
select owner||'.'||substr(object_name, 1, 30) as invalid_object,
       object_type
  from all_objects
 where status = 'INVALID'
   and owner in ('&cwms_schema', '&cwms_dba_schema')
 order by 1, 2;
prompt ################################################################################
prompt RECOMPILING SCHEMA
select systimestamp from dual;
exec sys.utl_recomp.recomp_serial('&cwms_schema');
prompt ################################################################################
prompt REMAINING INVALID OBJECTS...
select owner||'.'||substr(object_name, 1, 30) as invalid_object,
       object_type
  from all_objects
 where status = 'INVALID'
   and owner in ('&cwms_schema', '&cwms_dba_schema')
 order by 1, 2;
select owner||'.'||substr(name, 1, 30) as name,
       type,
       substr(line||':'||position, 1, 12) as location,
       substr(text, 1, 132) as error
  from all_errors
 where attribute = 'ERROR'
   and owner in ('&cwms_schema', '&cwms_dba_schema')
 order by owner, type, name, sequence;
prompt ################################################################################
prompt 'RESTORE CCP PRIVILEGES'
select systimestamp from dual;
whenever sqlerror continue;
declare
  l_count NUMBER;
begin
   select count(*) into l_count from dba_users where username='CCP';
   if(l_count>0)
   then
     for rec in (select object_name from user_objects where object_type in ('PACKAGE', 'TYPE')) loop
        execute immediate 'grant execute on '||rec.object_name||' to ccp';
     end loop;
   end if;
end;
/
whenever sqlerror exit;
prompt ################################################################################
prompt UPDATING DB_CHANGE_LOG
select systimestamp from dual;
@@./18_1_7/update_db_change_log
select substr(version, 1, 10) as version,
       to_char(version_date, 'yyyy-mm-dd hh24:mi') as version_date,
       to_char(apply_date, 'yyyy-mm-dd hh24:mi') as apply_date
  from av_db_change_log
 where application = 'CWMS'
 order by version_date;
prompt ################################################################################
prompt UPDATE COMPLETE
select systimestamp from dual;
exit

