DROP TABLE AT_SEC_SERVICE_USER;
CREATE TABLE AT_SEC_SERVICE_USER
(
  USERID   VARCHAR2(32) PRIMARY KEY,
  PASSWD   VARCHAR2(128),
  TIMEOUT  DATE
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;
