plugins {
    id 'database.deps-conventions'
    id 'base'
    id 'cwms.database.test-database' version 'local'
}

configurations {
    utplsql
}

dependencies {
    utplsql 'org.utplsql:utplsql:3.1.14@zip'
}

import cwms.database.testing.support.DatabaseService
def database = project.gradle.sharedServices.registerIfAbsent("database", DatabaseService) {} 

def downloadUtplSql = tasks.register("downloadUtplSql", Copy) {
    dependsOn checkTestSetup
    from zipTree(configurations.utplsql.singleFile)
    into "$buildDir/deps"
    doLast {
        File createOwner = new File("$buildDir/deps/utPLSQL/source/create_utplsql_owner.sql")
        createOwner.withWriterAppend( { out ->
            out.println("\ngrant execute on dbms_lob to &ut3_user;")
            out.println("grant execute on dbms_random to &ut3_user;")
	  		out.println("grant execute on dbms_random to &ut3_user;")
	  		out.println("grant execute on dbms_sql to &ut3_user;")
        })
    }
}

import cwms.database.testing.support.UtTest

def testAsPdUser = tasks.register("testAsPdUser", cwms.database.testing.support.UtTest) {
    dependsOn tasks.named("installTests")
    dependsOn tasks.named("loadTestData")
    //args "-p=${cwms_schema_name}.test_cwms_rating,${cwms_schema_name}.test_lrts_updates,${cwms_schema_name}.test_probability_parameter,${cwms_schema_name}.test_cwms_loc,${cwms_schema_name}.test_cwms_ts,${cwms_schema_name}.test_cwms_util,${cwms_schema_name}.test_cwms_prop,${cwms_schema_name}.test_versioned_time_series,${cwms_schema_name}.test_update_ts_extents,${cwms_schema_name}.test_cwms_pool,${cwms_schema_name}.test_timeseries_snapping,${cwms_schema_name}.test_cwms_cat,${cwms_schema_name}.test_cwms_msg,${cwms_schema_name}.test_cwms_level,${cwms_schema_name}.test_cwms_display"
    tests = ["test_cwms_level",
             "test_cwms_rating",
             "test_lrts_updates"]
    user = "cwmspd"
}

def testAsRoUser = tasks.register("testAsRoUser", cwms.database.testing.support.UtTest ) {
    dependsOn tasks.named("installTests")
    dependsOn tasks.named("loadTestData")
    tests = ["test_ro"]
    user = "hectest_ro"
}

test.dependsOn testAsPdUser
test.dependsOn testAsRoUser