plugins {
    id 'database.deps-conventions'
    id 'database'
    id 'base'
}

configurations {
    utplsql
}

dependencies {
    utplsql 'org.utplsql:utplsql:3.1.14@zip'
}

def cwms_schema_name = project.findProperty("cwms.schema") ?: "CWMS_20"
def cwms_office = project.findProperty("cwms.office") ?:"SPK"
def cwms_eroc = project.findProperty("cwms.eroc") ?:"l2"
def create_users = project.hasProperty("testaccounts") ? "create" : "nocreate"
def pd_password = project.findProperty("cwms.pd_password") ?: project.findProperty("flyway.password")
def test_password = project.findProperty("cwms.test_password") ?: pd_password
def coverageDir = "$buildDir/coverage"

var sysPassword = {database.buildUserPassword}
def cwms_user = {database.buildUser.get() + "[CWMS_20]"}

def checkTestSetup = tasks.register("checkTestSetup") {
    dependsOn startDatabase
    doFirst {
        def dbUrl = database.url.get()
        def result = exec {
            executable "sqlplus"
            args "-h"
            ignoreExitValue = true
            standardOutput = new ByteArrayOutputStream()
            errorOutput = new ByteArrayOutputStream()
        }

        if( result.getExitValue() !=0){
            throw new GradleException("sqlplus must be available for test framework to execute")
        }

        result = exec {
            executable "utplsql"
            args "-h"
            ignoreExitValue = true
            standardOutput = new ByteArrayOutputStream()
            errorOutput = new ByteArrayOutputStream()
        }

        if( result.getExitValue() != 0 ) {
            throw new GradleException("utplsql-cli must be installed and in PATH for tests to run")
        }


        if( sysPassword == null) {
            throw new GradleException("Tests can only be run if db.sys_password is set.")
        }

        if( dbUrl == null ){
            throw new GradleException("Test framework assumes you are allow running flyway Migrate tasks, please set flyway.url")
        }
    }
}

def downloadUtplSql = tasks.register("downloadUtplSql", Copy) {
    dependsOn checkTestSetup
    from zipTree(configurations.utplsql.singleFile)
    into "$buildDir/deps"
    doLast {
        File createOwner = new File("$buildDir/deps/utPLSQL/source/create_utplsql_owner.sql")
        createOwner.withWriterAppend( { out ->
            out.println("\ngrant execute on dbms_lob to &ut3_user;")
            out.println("grant execute on dbms_random to &ut3_user;")
	  		out.println("grant execute on dbms_random to &ut3_user;")
	  		out.println("grant execute on dbms_sql to &ut3_user;")
        })
    }
}

def installTestFramework = tasks.register("installTestFramework", DatabaseExecTask ) {
    dependsOn downloadUtplSql
    dependsOn checkTestSetup
    url = database.url
    user = database.buildUser
    password = database.buildUserPassword
    

    executable "sqlplus"
    argumentProviders.add({[
        String.format("%s/\"%s\"@%s as sysdba","sys", password.get(), url.get()),
        "@install_headless_with_trigger.sql"
    ]} as CommandLineArgumentProvider)
    ignoreExitValue true
    workingDir "$buildDir/deps/utPLSQL/source"
    doLast {
        exec {
            executable "sqlplus"
            argumentProviders.add({[
                String.format("sys/%s@%s as sysdba", password.get(), url.get())
            ]} as CommandLineArgumentProvider)
            standardInput = new ByteArrayInputStream("GRANT INHERIT PRIVILEGES ON USER sys TO ut3;".getBytes())

        }
    }
}


def installTests = tasks.register("installTests", DatabaseExecTask) {
    dependsOn installTestFramework
    dependsOn startDatabase
    url = database.url
    user = database.cwmsUser
    password = database.buildUserPassword
    sysPassword = database.buildUserPassword
    
    workingDir "src/test/utplsql"
    executable "sqlplus"
    argumentProviders.add({[
        String.format("%s/\"%s\"@%s", user.get(), password.get(), url.get()),
        "@tests.sql",
        cwms_office,
        cwms_schema_name,
        cwms_eroc + "hectest_up",
        cwms_eroc
    ]} as CommandLineArgumentProvider) 
    doLast {
        project.mkdir(coverageDir)
        exec {
            executable "sqlplus"
            workingDir "src/test/utplsql"
            argumentProviders.add({[
                String.format("sys/%s@%s as sysdba",sysPassword.get(),url.get()),
                "@test_grants.sql",
                "${cwms_eroc}cwmspd".toString(),
			    "${cwms_eroc}hectest_ro".toString(),
			    "${cwms_eroc}hectest_db".toString(),
			    "${cwms_eroc}hectest_pu".toString(),
			    "${cwms_eroc}hectest_up".toString(),
			    "${cwms_schema_name}".toString(),
                "${cwms_eroc}hectest".toString(),
                "${cwms_eroc}webtest".toString(),
                "${cwms_eroc}hectest_multioffice".toString()
            ]} as CommandLineArgumentProvider
            )        			
        }
    }
}

def cleanTestData = tasks.register("cleanTestData", DatabaseExecTask) {
    dependsOn installTests
    url = database.url
    user = database.cwmsUser
    password = database.buildUserPassword
    sysPassword = database.buildUserPassword
    executable="utplsql"
    argumentProviders.add({[
                "run",
                "-p=${cwms_schema_name}.test_clean_all".toString(),
                "-f=UT_COVERAGE_HTML_REPORTER",
                    "-o=${coverageDir}/index.html".toString(),
                "-f=UT_COVERAGE_COBERTURA_REPORTER",
                    "-o=${coverageDir}/coverage_pd.xml".toString(),
                "-f=UT_JUNIT_REPORTER",
                    "-o=$buildDir/tests_pd.xml".toString(),
                "-f=UT_DOCUMENTATION_REPORTER",
                "-d", // diagnostic info
                "-D", // dbms_output
                "-s", // terminal output even with o set
                "${user.get()}/\"${password.get()}\"@${url.get()}".toString()
            ]} as CommandLineArgumentProvider
            ) 
}

def loadTestData = tasks.register("loadTestData", DatabaseExecTask) {
    dependsOn installTests
    dependsOn cleanTestData
    url = database.url
    user = database.cwmsUser
    password = database.buildUserPassword

    workingDir "${projectDir}/src/test/data/ratings"
    executable "sqlldr"
    argumentProviders.add({[
        "${user.get()}/\"${password.get()}\"@${url.get()}".toString(),
        "control=xsl_test_clobs.ctl"
    ]} as CommandLineArgumentProvider)
}

def testAsPdUser = tasks.register("testAsPdUser", Exec) {
    dependsOn installTests
    dependsOn loadTestData
    url = database.url
    user = database.cwmsUser
    password = database.buildUserPassword
    executable "utplsql"
    args "run"
	//args "-p=${cwms_schema_name}.test_cwms_rating,${cwms_schema_name}.test_lrts_updates,${cwms_schema_name}.test_probability_parameter,${cwms_schema_name}.test_cwms_loc,${cwms_schema_name}.test_cwms_ts,${cwms_schema_name}.test_cwms_util,${cwms_schema_name}.test_cwms_prop,${cwms_schema_name}.test_versioned_time_series,${cwms_schema_name}.test_update_ts_extents,${cwms_schema_name}.test_cwms_pool,${cwms_schema_name}.test_timeseries_snapping,${cwms_schema_name}.test_cwms_cat,${cwms_schema_name}.test_cwms_msg,${cwms_schema_name}.test_cwms_level,${cwms_schema_name}.test_cwms_display"
    //args "-p=${cwms_schema_name}.test_cwms_loc,${cwms_schema_name}.test_cwms_ts"//,${cwms_schema_name}.test_cwms_util,${cwms_schema_name}.test_cwms_prop,${cwms_schema_name}.test_update_ts_extents,${cwms_schema_name}.test_cwms_display"
    args "-p=${cwms_schema_name}.test_cwms_level"
    args "-f=UT_COVERAGE_HTML_REPORTER"
        args "-o=${coverageDir}/index.html"
    args "-f=UT_COVERAGE_COBERTURA_REPORTER"
        args "-o=${coverageDir}/coverage_dba.xml"
    args "-f=UT_JUNIT_REPORTER"
        args "-o=$buildDir/tests_pdu.xml"
	args "-f=UT_DOCUMENTATION_REPORTER"
    args "-d" // diagnostic info
    args "-D" // dbms_output
    args "-s" // terminal output even with o set
    args "-c" // color
	args "${cwms_eroc}cwmspd/\"${pd_password}\"@${dbUrl}"
}

def testAsRoUser = tasks.register("testAsRoUser", Exec ) {
    dependsOn installTests
    dependsOn loadTestData
    def dbUrl = () -> database.url.get().split("@")[1]
    executable="utplsql"
    args "run"
	args "-p=${cwms_schema_name}.test_ro"
    args "-f=UT_COVERAGE_HTML_REPORTER"
        args "-o=${coverageDir}/index.html"
    args "-f=UT_COVERAGE_COBERTURA_REPORTER"
        args "-o=${coverageDir}/coverage_ro.xml"
    args "-f=UT_JUNIT_REPORTER"
        args "-o=$buildDir//tests_ro.xml"
	args "-f=UT_DOCUMENTATION_REPORTER"
    args "-d"
    args "-D"
    args "-s"
	args "${cwms_eroc}hectest_ro/\"${pd_password}\"@${dbUrl}"
}


def testDb = tasks.register("testDb") {    
    dependsOn installTests

    dependsOn cleanTestData
    dependsOn loadTestData
    dependsOn testAsPdUser
    //dependsOn testAsRoUser
}

def test = tasks.register("test") {
    dependsOn testDb
}
