CREATE TABLE "CWMS_USACE_DAM_COUNTY"
(
   "COUNTY_ID"     INTEGER,
   "STATE_ID"      INTEGER,
   "COUNTY_NAME"   VARCHAR2 (300 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
NOCOMPRESS
LOGGING
STORAGE (INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
TABLESPACE CWMS_20DATA;

ALTER TABLE CWMS_USACE_DAM_COUNTY
 ADD CONSTRAINT CWMS_USACE_DAM_COUNTY_U01
  UNIQUE (COUNTY_ID, STATE_ID, COUNTY_NAME)
  ENABLE VALIDATE;


REM INSERTING into CWMS_USACE_DAM_COUNTY
SET DEFINE OFF;

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (3, 25, 'ADAMS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (4, 23, 'AITKIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (5, 36, 'ALFALFA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (6, 46, 'ALLEGHANY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (7, 38, 'ALLEGHENY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (8, 40, 'ANDERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (9, 15, 'APPANOOSE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (10, 6, 'ARAPAHOE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (11, 4, 'ARKANSAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (12, 38, 'ARMSTRONG');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (13, 35, 'ASHLAND');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (14, 35, 'ATHENS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (15, 17, 'BALLARD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (16, 34, 'BARNES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (17, 17, 'BARREN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (18, 10, 'BARTOW');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (19, 17, 'BATH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (20, 4, 'BAXTER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (21, 38, 'BEAVER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (22, 43, 'BELL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (23, 6, 'BENT');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (24, 25, 'BENTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (25, 47, 'BENTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (26, 40, 'BERKELEY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (27, 38, 'BERKS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (28, 33, 'BLADEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (29, 36, 'BLAINE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (30, 12, 'BONNER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (31, 43, 'BOSQUE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (32, 18, 'BOSSIER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (33, 43, 'BOWIE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (34, 34, 'BOWMAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (35, 17, 'BRACKEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (36, 48, 'BRAXTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (37, 17, 'BRECKINRIDGE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (38, 32, 'BROOME');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (1, 40, 'ABBEVILLLE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (2, 12, 'ADA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (39, 13, 'BROWN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (40, 49, 'BROWN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (41, 36, 'BRYAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (42, 41, 'BUFFALO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (43, 49, 'BUFFALO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (44, 43, 'BURLESON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (45, 16, 'BUTLER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (46, 17, 'BUTLER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (47, 18, 'CADDO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (48, 5, 'CALAVERAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (49, 18, 'CALDWELL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (50, 41, 'CAMBELL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (51, 38, 'CARBON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (52, 4, 'CARROLL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (53, 35, 'CARROLL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (54, 17, 'CARTER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (55, 23, 'CASS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (56, 18, 'CATAHOULA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (57, 25, 'CEDAR');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (58, 38, 'CENTRE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (59, 43, 'CHAMBERS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (60, 41, 'CHARLES MIX');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (61, 33, 'CHATHAM');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (62, 31, 'CHAVES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (63, 42, 'CHEATHAM');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (64, 36, 'CHEROKEE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (65, 29, 'CHESHIRE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (66, 22, 'CHIPPEWA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (67, 23, 'CHIPPEWA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (68, 1, 'CHOCTAW');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (69, 36, 'CHOCTAW');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (70, 37, 'CLACKAMAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (71, 4, 'CLARK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (72, 35, 'CLARK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (73, 25, 'CLAY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (74, 42, 'CLAY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (75, 15, 'CLAYTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (76, 38, 'CLEARFIELD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (77, 12, 'CLEARWATER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (78, 23, 'CLEARWATER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (79, 4, 'CLEBURNE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (80, 35, 'CLERMONT');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (81, 13, 'CLINTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (82, 38, 'CLINTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (83, 16, 'COFFEY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (84, 43, 'COLEMAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (85, 43, 'COLLIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (86, 10, 'COLUMBIA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (87, 47, 'COLUMBIA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (88, 43, 'COMAL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (89, 43, 'COMANCHE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (90, 4, 'CONWAY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (91, 13, 'COOK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (92, 35, 'COSHOCTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (93, 47, 'COWLITZ');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (94, 38, 'CRAWFORD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (95, 49, 'CRAWFORD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (96, 36, 'CREEK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (97, 23, 'CROW WING');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (98, 23, 'DAKOTA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (99, 43, 'DALLAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (100, 42, 'DAVIDSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (101, 42, 'DE KALB');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (102, 35, 'DELAWARE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (103, 43, 'DENTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (104, 4, 'DESHA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (105, 24, 'DESOTO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (106, 46, 'DICKENSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (107, 6, 'DOUGLAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (108, 16, 'DOUGLAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (109, 27, 'DOUGLAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (110, 47, 'DOUGLAS AND OKANOGAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (111, 14, 'DUBOIS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (112, 15, 'DUBUQUE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (113, 17, 'EDMONSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (114, 10, 'ELBERT');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (115, 38, 'ELK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (116, 43, 'ELLIS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (117, 16, 'ELLSWORTH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (118, 32, 'ERIE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (119, 38, 'ERIE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (120, 2, 'FAIRBANKS - NORTH STAR BO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (121, 41, 'FALL RIVER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (122, 4, 'FAULKNER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (123, 38, 'FAYETTE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (124, 17, 'FLOYD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (125, 38, 'FOREST');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (126, 10, 'FORSYTH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (127, 4, 'FRANKLIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (128, 13, 'FRANKLIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (129, 14, 'FRANKLIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (130, 47, 'FRANKLIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (131, 5, 'FRESNO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (132, 9, 'GADSDEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (133, 17, 'GALLATIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (134, 4, 'GARLAND');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (135, 20, 'GARRETT');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (136, 16, 'GEARY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (137, 9, 'GLADES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (138, 23, 'GOODHUE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (139, 1, 'GREENE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (140, 17, 'GREENUP');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (141, 16, 'GREENWOOD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (142, 24, 'GRENADA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (143, 13, 'GRUNDY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (144, 31, 'GUADALUPE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (145, 35, 'GUERNSEY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (146, 1, 'HALE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (147, 35, 'HAMILTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (148, 21, 'HAMPDEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (149, 21, 'HAMPSHIRE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (150, 17, 'HANCOCK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (151, 48, 'HANCOCK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (152, 17, 'HARLAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (153, 27, 'HARLAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (154, 43, 'HARRIS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (155, 35, 'HARRISON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (156, 10, 'HART');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (157, 15, 'HENDERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (158, 17, 'HENDERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (159, 23, 'HENNEPIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (160, 1, 'HENRY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (161, 46, 'HENRY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (162, 25, 'HICKORY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (163, 35, 'HIGHLAND AND ROSS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (164, 43, 'HILL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (165, 29, 'HILLSBOROUGH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (166, 24, 'HOLMES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (167, 43, 'HOPKINS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (168, 1, 'HOUSTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (169, 4, 'HOWARD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (170, 41, 'HUGHES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (171, 38, 'HUNTINGDON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (172, 14, 'HUNTINGTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (173, 38, 'INDIANA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (174, 15, 'IOWA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (175, 23, 'ITASCA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (176, 24, 'ITAWAMBA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (177, 15, 'JACKSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (178, 25, 'JACKSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (179, 37, 'JACKSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (180, 43, 'JASPER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (181, 4, 'JEFFERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (182, 6, 'JEFFERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (183, 16, 'JEFFERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (184, 17, 'JEFFERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (185, 36, 'JEFFERSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (186, 15, 'JOHNSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (187, 17, 'JOHNSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (188, 48, 'KANAWHA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (189, 36, 'KAY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (190, 5, 'KERN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (191, 43, 'KING');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (192, 47, 'KING');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (193, 17, 'KNOTT');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (194, 35, 'KNOX');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (195, 16, 'LABETTE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (196, 23, 'LAC QUI PARLE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (197, 38, 'LACKAWANNA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (198, 43, 'LAMAR');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (199, 27, 'LANCASTER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (200, 37, 'LANE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (201, 6, 'LAS ANIMAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (202, 13, 'LASALLE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (203, 24, 'LAUDERDALE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (204, 17, 'LAUREL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (205, 17, 'LAWRENCE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (206, 36, 'LE FLORE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (207, 9, 'LEE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (208, 13, 'LEE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (209, 25, 'LEWIS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (210, 48, 'LEWIS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (211, 25, 'LINCOLN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (212, 26, 'LINCOLN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (213, 28, 'LINCOLN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (214, 37, 'LINN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (215, 7, 'LITCHFIELD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (216, 4, 'LITTLE RIVER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (217, 32, 'LIVINGSTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (218, 5, 'LOS ANGELES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (219, 1, 'LOWNDES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (220, 24, 'LOWNDES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (221, 38, 'LUZERNE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (222, 38, 'LUZERNE-CARBON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (223, 17, 'LYON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (224, 25, 'MACON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (225, 5, 'MADERA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (226, 13, 'MADISON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (227, 1, 'MARENGO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (228, 3, 'MARICOPA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (229, 15, 'MARION');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (230, 16, 'MARION');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (231, 43, 'MARION');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (232, 5, 'MARIPOSA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (233, 16, 'MARSHALL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (234, 9, 'MARTIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (235, 48, 'MASON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (236, 26, 'MCCONE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (237, 17, 'MCCRACKEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (238, 36, 'MCCURTAIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (239, 36, 'MCINTOSH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (240, 17, 'MCLEAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (241, 34, 'MCLEAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (242, 43, 'MCLENNAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (243, 46, 'MECKLENBURG');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (244, 48, 'MEIGS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (245, 5, 'MENDOCINO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (246, 5, 'MERCED');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (247, 15, 'MERCER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (248, 38, 'MERCER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (249, 29, 'MERRIMACK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (250, 14, 'MIAMI');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (251, 16, 'MIAMI');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (252, 48, 'MONONGALIA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (253, 1, 'MONROE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (254, 14, 'MONROE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (255, 24, 'MONROE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (256, 16, 'MONTGOMERY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (257, 16, 'MORRIS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (258, 37, 'MORROW');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (259, 37, 'MULTNOMAH-SKAMANIA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (260, 10, 'MURRAY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (261, 35, 'MUSKINGUM');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (262, 35, 'MUSKINGUM AND COSHOCTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (263, 36, 'MUSKOGEE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (264, 18, 'NATCHITOCHES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (265, 43, 'NAVARRO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (266, 5, 'NEVADA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (267, 7, 'NEW HAVEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (268, 48, 'NICHOLAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (269, 48, 'OHIO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (270, 17, 'OHIO/MUHLENBERG');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (271, 36, 'OKLAHOMA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (272, 5, 'ORANGE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (273, 45, 'ORANGE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (274, 16, 'OSAGE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (275, 36, 'OSAGE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (276, 32, 'OTSEGO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (277, 36, 'OTTAWA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (278, 23, 'OTTER TAIL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (279, 49, 'OUTAGAMIE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (280, 9, 'PALM BEACH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (281, 24, 'PANOLA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (282, 14, 'PARKE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (283, 17, 'PERRY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (284, 35, 'PICKAWAY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (285, 1, 'PICKENS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (286, 49, 'PIERCE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (287, 4, 'PIKE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (288, 17, 'PIKE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (289, 25, 'PIKE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (290, 3, 'PINAL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (291, 5, 'PLACER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (292, 15, 'POLK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (293, 13, 'POPE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (294, 35, 'PORTAGE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (295, 4, 'PULASKI');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (296, 36, 'PUSHMATAHA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (297, 14, 'PUTNAM');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (298, 48, 'PUTNAM');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (299, 25, 'RALLS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (300, 13, 'RANDOLPH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (301, 18, 'RAPIDES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (302, 18, 'RED RIVER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (303, 32, 'RENSSELAER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (304, 10, 'RICHMOND');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (305, 16, 'RILEY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (306, 31, 'RIO ARRIBA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (307, 5, 'RIVERSIDE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (308, 15, 'ROCK ISLAND');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (309, 36, 'ROGERS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (310, 16, 'RUSSELL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (311, 17, 'RUSSELL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (312, 5, 'SAN BERNARDINO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (313, 5, 'SAN JOAQUIN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (314, 5, 'SAN LUIS OBISPO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (315, 31, 'SAN MIGUEL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (316, 31, 'SANDOVAL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (317, 31, 'SANTA FE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (318, 27, 'SARPY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (319, 15, 'SCOTT');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (320, 4, 'SEBASTIAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (321, 36, 'SEQUOYAH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (322, 4, 'SEVIER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (323, 27, 'SEWARD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (324, 13, 'SHELBY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (325, 37, 'SHERMAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (326, 42, 'SMITH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (327, 5, 'SONOMA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (328, 17, 'SPENCER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (329, 9, 'ST LUCIE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (330, 18, 'ST TAMMANY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (331, 32, 'STEUBEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (332, 34, 'STUTSMAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (333, 48, 'SUMMERS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (334, 38, 'SUSQUEHANNA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (335, 25, 'TANEY');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (336, 43, 'TARRANT');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (337, 17, 'TAYLOR');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (338, 48, 'TAYLOR');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (339, 13, 'TAZEWELL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (340, 5, 'TEHAMA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (341, 36, 'TEXAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (342, 51, 'TIBES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (343, 38, 'TIOGA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (344, 24, 'TISHOMINGO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (345, 7, 'TOLLAND');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (346, 43, 'TOM GREEN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (347, 23, 'TRAVERSE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (348, 49, 'TREMPEALEAU');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (349, 10, 'TROUP');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (350, 35, 'TRUMBULL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (351, 5, 'TULARE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (352, 36, 'TULSA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (353, 1, 'TUSCALOOSA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (354, 35, 'TUSCARAWAS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (355, 35, 'TUSCARAWAS AND STARK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (356, 43, 'TYLER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (357, 37, 'UMATILLA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (358, 4, 'UNION');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (359, 14, 'UNION');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (360, 17, 'UNION');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (361, 49, 'VERNON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (362, 14, 'WABASH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (363, 36, 'WAGONER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (364, 33, 'WAKE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (365, 47, 'WALLA WALLA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (366, 34, 'WALSH');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (367, 15, 'WARREN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (368, 35, 'WARREN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (369, 38, 'WARREN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (370, 37, 'WASCO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (371, 18, 'WASHINGTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (372, 36, 'WASHINGTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (373, 48, 'WASHINGTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (374, 25, 'WAYNE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (375, 38, 'WAYNE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (376, 48, 'WAYNE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (377, 38, 'WESTMORELAND');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (378, 48, 'WETZEL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (379, 15, 'WHITESIDE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (380, 47, 'WHITMAN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (381, 1, 'WILCOX');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (382, 33, 'WILKES');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (383, 13, 'WILL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (384, 43, 'WILLIAMSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (385, 7, 'WINDHAM');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (386, 45, 'WINDHAM');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (387, 45, 'WINDSOR');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (388, 49, 'WINNEBAGO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (389, 23, 'WINONA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (390, 46, 'WISE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (391, 16, 'WOODSON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (392, 36, 'WOODWARD');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (393, 21, 'WORCESTER');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (394, 48, 'WYOMING AND MINGO');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (395, 24, 'YALOBUSHA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (396, 41, 'YANKTON');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (397, 4, 'YELL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (398, 38, 'YORK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (399, 5, 'YUBA AND NEVADA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (400, 3, 'YUMA');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (401, 39, 'PROVIDENCE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (421, 35, 'MAHONING');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (441, 14, 'LAKE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (422, 35, 'STARK');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (442, 35, 'MARION');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (481, 24, 'WARREN');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (461, 35, 'STARK AND CARROLL');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (462, 35, 'WAYNE');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (501, 34, 'WILLIAMS');

INSERT INTO CWMS_USACE_DAM_COUNTY (COUNTY_ID, STATE_ID, COUNTY_NAME)
     VALUES (463, 35, 'HIGHLAND');

--------------------------------------------------------
--  Constraints for Table CWMS_USACE_DAM_COUNTY
--------------------------------------------------------

  ALTER TABLE "CWMS_USACE_DAM_COUNTY" MODIFY ("COUNTY_NAME" NOT NULL ENABLE);
  ALTER TABLE "CWMS_USACE_DAM_COUNTY" MODIFY ("STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "CWMS_USACE_DAM_COUNTY" MODIFY ("COUNTY_ID" NOT NULL ENABLE);
