/* Formatted on 7/3/2014 12:12:19 PM (QP5 v5.215.12089.38647) */
CREATE TABLE CWMS_AGG_DISTRICT
(
   OFFICE_CODE   NUMBER,
   OBJECTID      NUMBER,
   NAME          VARCHAR2 (25 BYTE),
   SYMBOL        VARCHAR2 (3 BYTE),
   SHAPE         MDSYS.SDO_GEOMETRY
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO"
   STORE AS LOB (ENABLE STORAGE IN ROW
                 CHUNK 8192
                 PCTVERSION 10
                 CACHE LOGGING
                 STORAGE (INITIAL 64 K
                          NEXT 1 M
                          MINEXTENTS 1
                          MAXEXTENTS UNLIMITED
                          PCTINCREASE 0
                          BUFFER_POOL DEFAULT
                          FLASH_CACHE DEFAULT
                          CELL_FLASH_CACHE DEFAULT))
VARRAY "SHAPE"."SDO_ORDINATES"
   STORE AS LOB (ENABLE STORAGE IN ROW
                 CHUNK 8192
                 PCTVERSION 10
                 CACHE LOGGING
                 STORAGE (INITIAL 64 K
                          NEXT 1 M
                          MINEXTENTS 1
                          MAXEXTENTS UNLIMITED
                          PCTINCREASE 0
                          BUFFER_POOL DEFAULT
                          FLASH_CACHE DEFAULT
                          CELL_FLASH_CACHE DEFAULT))
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_AGG_DISTRICT_PK
   ON CWMS_AGG_DISTRICT (OFFICE_CODE)
   LOGGING
   NOPARALLEL
/

ALTER TABLE CWMS_AGG_DISTRICT ADD (
  CONSTRAINT CWMS_AGG_DISTRICT_PK
  PRIMARY KEY
  (OFFICE_CODE)
  USING INDEX CWMS_AGG_DISTRICT_PK
  ENABLE VALIDATE)
/

ALTER TABLE CWMS_AGG_DISTRICT ADD (
  CONSTRAINT CWMS_AGG_DISTRICT_FK01
  FOREIGN KEY (OFFICE_CODE)
  REFERENCES CWMS_OFFICE (OFFICE_CODE)
  ENABLE VALIDATE)
/
