alter user CWMS_DBA ${CWMS_DBA_AUTH};
alter user CWMS_DBA account unlock;


-- This grants connect role
GRANT CREATE SESSION TO CWMS_DBA;
GRANT SET CONTAINER TO CWMS_DBA;
ALTER USER CWMS_DBA DEFAULT ROLE ALL;
  -- 4 System Privileges for CWMS_DBA
GRANT ALTER USER TO CWMS_DBA;
GRANT CREATE USER TO CWMS_DBA;
GRANT CREATE SESSION TO "CWMS_DBA" WITH ADMIN OPTION;
GRANT DROP USER TO "CWMS_DBA";
GRANT SELECT ANY DICTIONARY TO "CWMS_DBA";
