name: 'Start Oracle Database and Install Cwms Schema'
runs:
  using: "composite"
  steps:
    - name: Oracle Tools
      id: cache-oracle-tools
      uses: ./.github/actions/setup-oracle-clients
    - name: Prep Database
      shell: bash
      working-directory: schema
      run: ./gradlew schema:startDatabase --info
    - name: Install Schema
      shell: bash
      working-directory: schema
      run: ./gradlew schema:run --info -Pflyway.configFiles=build/flyway.config