name: 'Start Oracle Database and Install Cwms Schema'
runs:
  using: "composite"
  steps:
    - name: Oracle Tools
      id: cache-oracle-tools
      uses: ./.github/actions/setup-oracle-clients
    - name: Prep Database
      shell: bash
      run: ./gradlew schema:build integrationtests:installSchema --info
    