name: 'Start Oracle Database and Install Cwms Schema'
runs:
  using: "composite"
  steps:
    - name: Oracle Tools
      id: cache-oracle-tools
      uses: ./.github/actions/setup-oracle-clients
    - name: Prep Database
      shell: bash
      working-directory: schema
      run: ant docker.prepdb -Doracle.image=gvenzl/oracle-free:23.4-full-faststart
    - name: Install Schema
      shell: bash
      working-directory: schema
      run: ant docker.install -Doracle.image=gvenzl/oracle-free:23.4-full-faststart