CREATE TABLE CWMS_CITIES_SP
(
   "OBJECTID"     INTEGER NOT NULL ENABLE,
   "CITY_FIPS"    VARCHAR2 (5 BYTE),
   "CITY_NAME"    VARCHAR2 (40 BYTE),
   "STATE_FIPS"   VARCHAR2 (2 BYTE),
   "STATE_NAME"   VARCHAR2 (25 BYTE),
   "STATE_CITY"   VARCHAR2 (7 BYTE),
   "TYPE"         VARCHAR2 (25 BYTE),
   "CAPITAL"      VARCHAR2 (1 BYTE),
   "SHAPE"        "MDSYS"."SDO_GEOMETRY"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
NOCOMPRESS
LOGGING
STORAGE (INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
TABLESPACE CWMS_20DATA;


ALTER TABLE CWMS_20.CWMS_CITIES_SP
 ADD CONSTRAINT CWMS_CITIES_SP_U1
  UNIQUE (STATE_CITY)
  ENABLE VALIDATE;

