CREATE type TURBINE_SETTING_OBJ_T
/**
 * Holds information about a turbine setting at a CWMS project
 *
 * @see type turbine_setting_tab_t
 * @see type turbine_change_obj_t
 *
 * @member turbine_location_ref Identifies the turbine
 * @member old_discharge        The discharge through the turbine before the setting
 * @member new_discharge        The discharge through the turbine after the setting
 * @member discharge_units      The discharge unit
 * @member real_power           The actual power generated by the turbine after the setting
 * @member scheduled_load       The scheduled load for the turbine at the time of the setting
 * @member generation_units     The unit of power generation and load
 */
AS
  object
  (
  --required
  turbine_location_ref location_ref_t,
  old_discharge binary_double,
  new_discharge binary_double,
  --setting lookup?
  --discharge lookup?

  --not required
  discharge_units varchar2(16),
  real_power binary_double,
  scheduled_load binary_double,
  generation_units varchar2(16)
);
/


create or replace public synonym cwms_t_TURBINE_SETTING_OBJ for TURBINE_SETTING_OBJ_T;

