create unique index at_loc_lvl_indicator_u1 on at_loc_lvl_indicator (
   location_code,
   specified_level_code,
   parameter_code,
   duration_code,
   level_indicator_id,
   &cwms_schema..cwms_rounding.round_f(attr_value,12),
   attr_parameter_code,
   ref_specified_level_code,
   ref_attr_value);
---------------------------------------------------------
create unique index at_fcst_spec_idx2 on at_fcst_spec (
   &cwms_schema..cwms_util.get_db_office_id_from_code(office_code),
   fcst_spec_id,
   fcst_designator);
---------------------------------------------------------
@@cwms/views/av_basin.sql
@@cwms/views/av_loc.sql
@@cwms/views/av_loc2.sql
@@cwms/views/av_log_message.sql
@@cwms/views/av_stream.sql
@@cwms/views/av_stream_location.sql
@@cwms/views/av_stream_reach.sql
@@cwms/views/av_ts_alias.sql
@@cwms/views/av_ts_grp_assgn.sql
@@cwms/views/av_ts_cat_grp.sql
@@cwms/views/av_loc_lvl_attribute.sql
@@cwms/views/av_loc_lvl_ts_map.sql
@@cwms/views/av_loc_lvl_cur_max_ind.sql
@@cwms/views/av_embankment.sql
@@cwms/views/av_embank_protection_type.sql
@@cwms/views/av_embank_structure_type.sql
@@cwms/views/av_water_user_contract.sql
@@cwms/views/av_water_user_contract2.sql
@@cwms/views/av_forecast
@@cwms/views/av_forecast_ex
@@cwms/views/av_forecast_spec
@@cwms/views/av_application_login
@@cwms/views/av_application_session
@@cwms/views/av_loc_vert_datum
@@cwms/views/av_tsv_elev
@@cwms/views/av_cwms_user
@@cwms/views/av_ts_profile
@@cwms/views/av_ts_profile_parser
@@cwms/views/av_ts_profile_parser_param
@@cwms/views/av_ts_profile_inst
@@cwms/views/av_ts_profile_inst_ts
@@cwms/views/av_location_level2
@@cwms/views/av_virtual_location_level
@@cwms/views/av_vloc_lvl_constituent
---------------------------------------------------------
COMMIT;
