CREATE SMALLFILE TABLESPACE "CWMS_20AT_DATA" DATAFILE '/orabase/oradata/Q0CWMST1/cwms_dev_at_data_01' SIZE 200M AUTOEXTEND ON NEXT 200M MAXSIZE 2G LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
CREATE SMALLFILE TABLESPACE "CWMS_20DATA" DATAFILE '/orabase/oradata/Q0CWMST1/cwms_dev_data_01' SIZE 500M AUTOEXTEND ON NEXT 200M MAXSIZE 2G LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
CREATE SMALLFILE TABLESPACE "CWMS_20_TSV" DATAFILE '/orabase/oradata/Q0CWMST1/cwms_dev_tsv_01' SIZE 500M AUTOEXTEND ON NEXT 200M MAXSIZE 2G LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
