CREATE TABLE AT_SEC_CWMS_USERS
(
  USERID     VARCHAR2(31 BYTE)                  NOT NULL,
  FULLNAME   VARCHAR2(96 BYTE),
  PHONE      VARCHAR2(16 BYTE),
  OFFICE     VARCHAR2(16 BYTE),
  ORG        VARCHAR2(16 BYTE),
  EMAIL      VARCHAR2(128 BYTE),
  CREATEDBY  VARCHAR2(32 BYTE)
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AT_SEC_CWMS_USERS_PK ON AT_SEC_CWMS_USERS
(USERID)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER AT_SEC_CWMS_USERS_TRIG
    BEFORE INSERT OR UPDATE OF userid
    ON AT_SEC_CWMS_USERS     REFERENCING NEW AS new OLD AS old
    FOR EACH ROW
DECLARE
BEGIN
    :new.userid := UPPER (:new.userid);
END;
/


ALTER TABLE AT_SEC_CWMS_USERS ADD (
  CONSTRAINT AT_SEC_CWMS_USERS_PK
  PRIMARY KEY
  (USERID)
  USING INDEX AT_SEC_CWMS_USERS_PK)
/

CREATE TABLE CWMS_20.AT_SEC_CWMS_PERMISSIONS
(
  USERNAME        VARCHAR2(31 BYTE)             NOT NULL,
  DB_OFFICE_CODE  NUMBER,
  PERMISSIONS     VARCHAR2(1028 BYTE)           NOT NULL
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING

/

COMMENT ON TABLE CWMS_20.AT_SEC_CWMS_PERMISSIONS IS 'Table to store CWMS PERMISSIONS in the database'

/



CREATE UNIQUE INDEX CWMS_20.AT_SEC_CWMS_PERMISSIONS_PK1 ON CWMS_20.AT_SEC_CWMS_PERMISSIONS
(USERNAME,DB_OFFICE_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL

/


ALTER TABLE CWMS_20.AT_SEC_CWMS_PERMISSIONS ADD (
  CONSTRAINT AT_SEC_CWMS_PERMISSIONS_PK1
  PRIMARY KEY
  (USERNAME,DB_OFFICE_CODE)
  USING INDEX CWMS_20.AT_SEC_CWMS_PERMISSIONS_PK1)

/

ALTER TABLE CWMS_20.AT_SEC_CWMS_PERMISSIONS ADD (
  CONSTRAINT AT_SEC_CWMS_PERMISSIONS_FK1 
  FOREIGN KEY (DB_OFFICE_CODE) 
  REFERENCES CWMS_20.CWMS_OFFICE (OFFICE_CODE),
  CONSTRAINT AT_SEC_CWMS_PERMISSIONS_FK2 
  FOREIGN KEY (USERNAME) 
  REFERENCES CWMS_20.AT_SEC_CWMS_USERS (USERID))

/

