
--
-- INSERT AT_AGENCY_NAME --
--
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (1,'SHEF', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), 'Standard Hydrometeorologic Exchange Format');
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (2,'GOES', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),'Geostationary Operational Environmental Satellite');
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (3,'CBT', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),'Columbia Basin Trust');
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (4,'NWS_HB5', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),'National Weather Service HandBook 5');
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (5,'USGS', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),'U.S. Geological Survey');
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (6,'SnoTel', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),'NRCS SNOwpack TELemetry');
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (7,'USBR', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),'U.S. Deptartment of the Interior, Bureau of Reclamation');
--INSERT INTO AT_AGENCY_NAME (AGENCY_CODE, AGENCY_ID, DB_OFFICE_CODE, AGENCY_NAME)
--    VALUES (8,'NRCS', (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),'Natural Resources Conservation Service ');

--------------------
-- load table data --
---------------------
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'PERCENT',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'),
    (    SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='%'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='None'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'percent',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='%'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='None'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 sq m',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='1000 m2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 sq meters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='1000 m2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 cu m',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='1000 m3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Celcius',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Centigrade',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'DEG C',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'deg C',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'DEG-C',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Deg-C',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'DegC',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'degC',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='C'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'DEG F',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='F'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'deg F',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='F'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'DEG-F',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='F'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Deg-F',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='F'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'DegF',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='F'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'degF',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='F'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Fahrenheit',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='F'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Temperature'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'ACFT',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ac-ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'AC-FT',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ac-ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'acft',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ac-ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'acre-feet',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ac-ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'acre-ft',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ac-ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'acres',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='acre'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'CFS',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu-ft/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cuft/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cusecs',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'ft3/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'centimeter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'centimeters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'CMS',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cms'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu-meters/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cms'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'M3/S',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cms'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'm3/s',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cms'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'm3/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='cms'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'FEET',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'FT',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'feet',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'foot',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'fps',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft/s'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Linear Speed'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'ft/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft/s'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Linear Speed'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq ft',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'square feet',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ft2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'gm/l',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='g/l'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Mass Concentration'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'grams per liter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='g/l'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Mass Concentration'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'grams/liter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='g/l'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Mass Concentration'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'GAL',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='gal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'gallon',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='gal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'gallons',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='gal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Gal/min',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='gpm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'gallons per minute',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='gpm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'GPM',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='gpm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'hectare',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ha'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'hectares',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='ha'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'hour',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='hr'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Elapsed Time'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'hours',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='hr'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Elapsed Time'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'inch',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='in'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'IN',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='in'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'INCHES',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='in'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'inches',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='in'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'jtu',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='JTU'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Turbidity'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'kN/m2',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kPa'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Pressure'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 ac-ft',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kaf'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 cfs',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kcfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 cu-ft/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kcfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 ft3/sec',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kcfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'KCFS',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kcfs'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 gallon',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    '1000 gallons',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'KGAL',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'TGAL',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'tgal',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='kgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'kilometer',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='km'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'kilometers',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='km'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq km',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='km2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq.km',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='km2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sqkm',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='km2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu km',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='km3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'lbs',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='lb'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Force'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'meter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'meters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'metre',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'metres',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq m',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq meter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq meters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'square meters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu m',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu meter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu meters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cubic meters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='m3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'mbar',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mb'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Pressure'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'mbars',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mb'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Pressure'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'millibar',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mb'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Pressure'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'millibars',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mb'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Pressure'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'millgrams/liter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mg/l'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Mass Concentration'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'milligrams per liter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mg/l'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Mass Concentration'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'MGAL',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'million gallon',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'millon gallons',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mgal'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'MGD',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mgd'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'million gallons/day',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mgd'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume Rate'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'mile',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mi'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'miles',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mi'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'mi2',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mile2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq mi',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mile2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq mile',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mile2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'sq miles',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mile2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'square miles',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mile2'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Area'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu mile',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mile3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'cu miles',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mile3'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Volume'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'minute',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='min'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Elapsed Time'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'minutes',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='min'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Elapsed Time'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'millimeter',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'millimeters',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='mm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Length'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'ntu',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='NTU'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Turbidity'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'lbs/sqin',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='psi'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Pressure'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'rev/min',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='rpm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Angular Speed'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'revolutions per minute',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='rpm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Angular Speed'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'second',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='sec'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Elapsed Time'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'seconds',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='sec'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Elapsed Time'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'umhos/cm',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='umho/cm'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Conductivity'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'VOLT',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='volt'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Electromotive Potential'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Volt',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='volt'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Electromotive Potential'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'VOLTS',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='volt'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Electromotive Potential'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'Volts',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='volt'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Electromotive Potential'
        )
    )
);
INSERT INTO AT_UNIT_ALIAS (ALIAS_ID, DB_OFFICE_CODE, UNIT_CODE) VALUES (
    'volts',
    (SELECT OFFICE_CODE FROM CWMS_OFFICE WHERE OFFICE_ID = 'CWMS'), (SELECT UNIT_CODE
        FROM   CWMS_UNIT
        WHERE  UNIT_ID='volt'
        AND    ABSTRACT_PARAM_CODE=
        (    SELECT ABSTRACT_PARAM_CODE
            FROM   CWMS_ABSTRACT_PARAMETER 
            WHERE  ABSTRACT_PARAM_ID='Electromotive Potential'
        )
    )
);
