CREATE TABLE AT_SEC_CWMS_USERS
(
  USERID     VARCHAR2(31 BYTE)                  NOT NULL,
  FULLNAME   VARCHAR2(96 BYTE),
  PHONE      VARCHAR2(24 BYTE),
  OFFICE     VARCHAR2(16 BYTE),
  ORG        VARCHAR2(16 BYTE),
  EMAIL      VARCHAR2(128 BYTE),
  CREATEDBY  VARCHAR2(32 BYTE),
  PRINCIPLE_NAME  VARCHAR2(128 BYTE),
  EDIPI           INTEGER Generated Always as (CASE  WHEN LENGTH("PRINCIPLE_NAME")>10 THEN CASE  WHEN  REGEXP_LIKE (SUBSTR("PRINCIPLE_NAME",1,10),'^[[:digit:]]+$') THEN TO_NUMBER(SUBSTR("PRINCIPLE_NAME",1,10)) ELSE NULL END  ELSE NULL END)
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX AT_SEC_CWMS_USERS_PK ON AT_SEC_CWMS_USERS
(USERID)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE OR REPLACE TRIGGER AT_SEC_CWMS_USERS_TRIG
    BEFORE INSERT OR UPDATE OF userid
    ON AT_SEC_CWMS_USERS     REFERENCING NEW AS new OLD AS old
    FOR EACH ROW
DECLARE
BEGIN
    :new.userid := UPPER (:new.userid);
END;
/


ALTER TABLE AT_SEC_CWMS_USERS ADD (
  CONSTRAINT AT_SEC_CWMS_USERS_PK
  PRIMARY KEY
  (USERID)
  USING INDEX AT_SEC_CWMS_USERS_PK)
/

CREATE TABLE AT_SEC_USER_OFFICE
(
  USERNAME        VARCHAR2(31 BYTE)             NOT NULL,
  DB_OFFICE_CODE  NUMBER
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING

/

COMMENT ON TABLE AT_SEC_USER_OFFICE IS 'Table to indicate whether a user has any permissions for a given office'

/



CREATE UNIQUE INDEX AT_SEC_USER_OFFICE_PK ON AT_SEC_USER_OFFICE
(USERNAME,DB_OFFICE_CODE)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL

/


ALTER TABLE AT_SEC_USER_OFFICE ADD (
  CONSTRAINT AT_SEC_USER_OFFICE_PK
  PRIMARY KEY
  (USERNAME,DB_OFFICE_CODE)
  USING INDEX AT_SEC_USER_OFFICE_PK)

/

ALTER TABLE AT_SEC_USER_OFFICE ADD (
  CONSTRAINT AT_SEC_USER_OFFICE_FK1
  FOREIGN KEY (DB_OFFICE_CODE) 
  REFERENCES CWMS_OFFICE (OFFICE_CODE),
  CONSTRAINT AT_SEC_USER_OFFICE_FK2 
  FOREIGN KEY (USERNAME) 
  REFERENCES AT_SEC_CWMS_USERS (USERID))

/

CREATE OR REPLACE TRIGGER AT_SEC_USER_OFFICE_TRIG
        BEFORE INSERT OR UPDATE OF username
        ON AT_SEC_USER_OFFICE
        REFERENCING NEW AS new OLD AS old
        FOR EACH ROW
DECLARE
BEGIN
        :new.username := UPPER (:new.username);
END;
/

CREATE TABLE AT_SEC_SESSION
(
  USERID         VARCHAR2(32 BYTE),
  SESSION_KEY    VARCHAR2(128 BYTE),
  TIMEOUT        TIMESTAMP(6)
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

CREATE TABLE AT_SEC_SERVICE_USER
(
  USERID   VARCHAR2(32 BYTE) PRIMARY KEY,
  PASSWD   VARCHAR2(128 BYTE),
  TIMEOUT  DATE
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;
