SET define on
@@defines.sql


CREATE TABLE AT_XCHG_DATASTORE_DSS
(
  DATASTORE_CODE  NUMBER(10)         NOT NULL,
  OFFICE_CODE     NUMBER(10)         NOT NULL,
  DATASTORE_ID    VARCHAR2(32)       NOT NULL,
  DSS_FILEMGR_URL VARCHAR2(255 BYTE) NOT NULL,
  DSS_FILE_NAME   VARCHAR2(255 BYTE) NOT NULL,
  DESCRIPTION     VARCHAR2(255 BYTE),
  CONSTRAINT AT_XCHG_DATASTORE_DSS_PK  PRIMARY KEY (DATASTORE_CODE) USING INDEX,
  CONSTRAINT AT_XCHG_DATASTORE_DSS_UK1 UNIQUE (OFFICE_CODE, DATASTORE_ID) USING INDEX
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             200K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE AT_XCHG_DATASTORE_DSS IS 'Contains location information for HEC-DSS files';
COMMENT ON COLUMN AT_XCHG_DATASTORE_DSS.DATASTORE_CODE IS 'Primary key used to relate file to other entities';
COMMENT ON COLUMN AT_XCHG_DATASTORE_DSS.OFFICE_CODE IS 'Reference to owning office';
COMMENT ON COLUMN AT_XCHG_DATASTORE_DSS.DATASTORE_ID IS 'Text identifier of datastore - unique within an office';
COMMENT ON COLUMN AT_XCHG_DATASTORE_DSS.DSS_FILEMGR_URL IS 'URL For DSSFileManager instance for HEC-DSS file';
COMMENT ON COLUMN AT_XCHG_DATASTORE_DSS.DSS_FILE_NAME IS 'Operating system path name for file';
COMMENT ON COLUMN AT_XCHG_DATASTORE_DSS.DESCRIPTION IS 'Text description of datastore - optional';

ALTER TABLE AT_XCHG_DATASTORE_DSS ADD CONSTRAINT AT_XCHG_DATASTORE_DSS_FK1 FOREIGN KEY (OFFICE_CODE) REFERENCES CWMS_OFFICE (OFFICE_CODE);


CREATE TABLE AT_XCHG_SET
(
  XCHG_SET_CODE      NUMBER(10)                 NOT NULL,
  DATASTORE_CODE     NUMBER(10)                 NOT NULL,
  OFFICE_CODE        NUMBER(10)                 NOT NULL,
  XCHG_SET_ID        VARCHAR2(32 BYTE)          NOT NULL,
  DESCRIPTION        VARCHAR2(80 BYTE),
  START_TIME         VARCHAR2(32 BYTE),
  END_TIME           VARCHAR2(32 BYTE),
  INTERPOLATE_COUNT  NUMBER(10)                 DEFAULT 0,
  INTERPOLATE_UNITS  NUMBER(1)                  DEFAULT 1,
  REALTIME           NUMBER,
  LAST_UPDATE        TIMESTAMP(6),
  OVERRIDE_TIME_ZONE VARCHAR2(28),
  CONSTRAINT AT_XCHG_SET_PK  PRIMARY KEY (XCHG_SET_CODE) USING INDEX,
  CONSTRAINT AT_XCHG_SET_U1  UNIQUE (OFFICE_CODE, XCHG_SET_ID) USING INDEX
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             200K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE AT_XCHG_SET IS 'Oracle/HEC-DSS exchange set specification';
COMMENT ON COLUMN AT_XCHG_SET.XCHG_SET_CODE IS 'Primary key used to relate specification to other entities';
COMMENT ON COLUMN AT_XCHG_SET.DATASTORE_CODE IS 'Reference to DSS datastore';
COMMENT ON COLUMN AT_XCHG_SET.OFFICE_CODE IS 'Reference to CWMS office';
COMMENT ON COLUMN AT_XCHG_SET.XCHG_SET_ID IS 'Text identifier of exchange set';
COMMENT ON COLUMN AT_XCHG_SET.DESCRIPTION IS 'Text description of exchange set';
COMMENT ON COLUMN AT_XCHG_SET.START_TIME IS 'Parameterized or explicit start of time window';
COMMENT ON COLUMN AT_XCHG_SET.END_TIME IS 'Parameterized or explicit end of time window';
COMMENT ON COLUMN AT_XCHG_SET.INTERPOLATE_COUNT IS 'Maximum number over which to interpolate on exchange';
COMMENT ON COLUMN AT_XCHG_SET.INTERPOLATE_UNITS IS 'Units of interpolation';
COMMENT ON COLUMN AT_XCHG_SET.REALTIME IS 'Reference to realtime exchange direction or NULL if not realtime';
COMMENT ON COLUMN AT_XCHG_SET.LAST_UPDATE IS 'Timestamp of last realtime exchange';
COMMENT ON COLUMN AT_XCHG_SET.OVERRIDE_TIME_ZONE IS 'Interpret DSS times in this time zone regardless of other info';

ALTER TABLE AT_XCHG_SET ADD CONSTRAINT AT_XCHG_SET_CK1 CHECK (INTERPOLATE_COUNT >= 0);
ALTER TABLE AT_XCHG_SET ADD CONSTRAINT AT_XCHG_SET_FK1 FOREIGN KEY (DATASTORE_CODE) REFERENCES AT_XCHG_DATASTORE_DSS (DATASTORE_CODE);
ALTER TABLE AT_XCHG_SET ADD CONSTRAINT AT_XCHG_SET_FK2 FOREIGN KEY (OFFICE_CODE) REFERENCES CWMS_OFFICE (OFFICE_CODE);
ALTER TABLE AT_XCHG_SET ADD CONSTRAINT AT_XCHG_SET_FK3 FOREIGN KEY (REALTIME) REFERENCES CWMS_DSS_XCHG_DIRECTION (DSS_XCHG_DIRECTION_CODE);
ALTER TABLE AT_XCHG_SET ADD CONSTRAINT AT_XCHG_SET_FK4 FOREIGN KEY (INTERPOLATE_UNITS) REFERENCES CWMS_INTERPOLATE_UNITS (INTERPOLATE_UNITS_CODE);


CREATE TABLE AT_XCHG_DSS_TS_MAPPINGS
(
  MAPPING_CODE            NUMBER(10)    NOT NULL,
  XCHG_SET_CODE           NUMBER(10)    NOT NULL,
  CWMS_TS_CODE            NUMBER(10)    NOT NULL,
  A_PATHNAME_PART         VARCHAR2(64),
  B_PATHNAME_PART         VARCHAR2(64)  NOT NULL,
  C_PATHNAME_PART         VARCHAR2(64)  NOT NULL,
  E_PATHNAME_PART         VARCHAR2(64)  NOT NULL,
  F_PATHNAME_PART         VARCHAR2(64),
  DSS_PARAMETER_TYPE_CODE NUMBER(10)    NOT NULL,
  UNIT_ID                 VARCHAR2(16)  NOT NULL,
  TIME_ZONE_CODE          NUMBER(10)    NOT NULL,
  TZ_USAGE_CODE           NUMBER(10)    NOT NULL,
  CONSTRAINT AT_XCHG_DSS_TS_MAPPINGS_PK  PRIMARY KEY (MAPPING_CODE, XCHG_SET_CODE, CWMS_TS_CODE) USING INDEX,
  CONSTRAINT AT_XCHG_DSS_TS_MAPPINGS_U1  UNIQUE (XCHG_SET_CODE, CWMS_TS_CODE) USING INDEX
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             200K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE AT_XCHG_DSS_TS_MAPPINGS IS 'Mappings of Oracle time series to DSS datasets';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.MAPPING_CODE IS 'Primary key used to relate specification to other entities';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.XCHG_SET_CODE IS 'Reference to dataexchange set';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.CWMS_TS_CODE IS 'Reference to CWMS Time series';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.A_PATHNAME_PART IS 'DSS A part';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.B_PATHNAME_PART IS 'DSS B part';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.C_PATHNAME_PART IS 'DSS C part';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.E_PATHNAME_PART IS 'DSS E part';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.F_PATHNAME_PART IS 'DSS F part';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.DSS_PARAMETER_TYPE_CODE IS 'Reference to DSS parameter type';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.UNIT_ID IS 'Units of DSS dataset';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.TIME_ZONE_CODE IS 'Reference to Time zone for DSS dataset';
COMMENT ON COLUMN AT_XCHG_DSS_TS_MAPPINGS.TZ_USAGE_CODE IS 'Reference to time zone usage for DSS dataset';

ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS ADD CONSTRAINT AT_XCHG_DSS_TS_MAPPINGS_FK1 FOREIGN KEY (XCHG_SET_CODE) REFERENCES AT_XCHG_SET (XCHG_SET_CODE);
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS ADD CONSTRAINT AT_XCHG_DSS_TS_MAPPINGS_FK2 FOREIGN KEY (CWMS_TS_CODE) REFERENCES AT_CWMS_TS_SPEC (TS_CODE);
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS ADD CONSTRAINT AT_XCHG_DSS_TS_MAPPINGS_FK3 FOREIGN KEY (DSS_PARAMETER_TYPE_CODE) REFERENCES CWMS_DSS_PARAMETER_TYPE (DSS_PARAMETER_TYPE_CODE);
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS ADD CONSTRAINT AT_XCHG_DSS_TS_MAPPINGS_FK4 FOREIGN KEY (TIME_ZONE_CODE) REFERENCES CWMS_TIME_ZONE (TIME_ZONE_CODE);
ALTER TABLE AT_XCHG_DSS_TS_MAPPINGS ADD CONSTRAINT AT_XCHG_DSS_TS_MAPPINGS_FK5 FOREIGN KEY (TZ_USAGE_CODE) REFERENCES CWMS_TZ_USAGE(TZ_USAGE_CODE);

CREATE INDEX AT_XCHG_DSS_TS_MAPPINGS_IDX1 ON AT_XCHG_DSS_TS_MAPPINGS
(UPPER("B_PATHNAME_PART"),
 UPPER("C_PATHNAME_PART"),
 UPPER("E_PATHNAME_PART"),
 UPPER("A_PATHNAME_PART"),
 UPPER("F_PATHNAME_PART"))
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          200K
            NEXT             200K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

-----------------------------
-- at_unit_alias trigger (depends on at_xchg_dss_ts_mappings)
--
create or replace trigger at_unit_alias_constraint
before delete or update
of alias_id
on "&cwms_schema"."AT_UNIT_ALIAS" 
referencing new as new old as old
for each row
declare
   l_count number;   
begin
   if deleting or (updating and :new.alias_id != :old.alias_id) then
      select count(unit_id)
        into l_count
        from at_xchg_dss_ts_mappings m,
             at_cwms_ts_spec         ts,
             at_physical_location    pl,
             at_base_location        bl,
             cwms_office             o
       where m.unit_id = :old.alias_id
         and ts.ts_code = m.cwms_ts_code
         and pl.location_code = ts.location_code
         and bl.base_location_code = pl.base_location_code
         and o.office_code = bl.db_office_code
         and o.office_code = :old.db_office_code;
      if l_count > 0 then
         cwms_err.raise(
            'cannot_delete_unit_1',
            :old.alias_id,
            ''|| l_count || 'dss time series specification(s)');
      end if;
   end if;
end at_unit_alias_constraint;
/
show errors;
commit;

