



CREATE TABLE CWMS_SHEF_TIME_ZONE
(
  SHEF_TIME_ZONE_CODE  NUMBER,
  SHEF_TIME_ZONE_ID    VARCHAR2(16 BYTE)        NOT NULL,
  SHEF_TIME_ZONE_DESC  VARCHAR2(64 BYTE)
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_SHEF_TIME_ZONE_PK ON CWMS_SHEF_TIME_ZONE
(SHEF_TIME_ZONE_CODE)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE CWMS_SHEF_TIME_ZONE ADD (
  CONSTRAINT CWMS_SHEF_TIME_ZONE_PK
 PRIMARY KEY
 (SHEF_TIME_ZONE_CODE)
    USING INDEX 
    TABLESPACE CWMS_20AT_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ))
/
SET DEFINE OFF;
Insert into CWMS_SHEF_TIME_ZONE
   (SHEF_TIME_ZONE_CODE, SHEF_TIME_ZONE_ID, SHEF_TIME_ZONE_DESC)
 Values
   (2, 'PST', 'Pacific Standard Time');
Insert into CWMS_SHEF_TIME_ZONE
   (SHEF_TIME_ZONE_CODE, SHEF_TIME_ZONE_ID, SHEF_TIME_ZONE_DESC)
 Values
   (3, 'MST', 'Mountain Standard Time');
Insert into CWMS_SHEF_TIME_ZONE
   (SHEF_TIME_ZONE_CODE, SHEF_TIME_ZONE_ID, SHEF_TIME_ZONE_DESC)
 Values
   (4, 'CST', 'Central Standard Time');
Insert into CWMS_SHEF_TIME_ZONE
   (SHEF_TIME_ZONE_CODE, SHEF_TIME_ZONE_ID, SHEF_TIME_ZONE_DESC)
 Values
   (5, 'EST', 'Eastern Standard Time');
Insert into CWMS_SHEF_TIME_ZONE
   (SHEF_TIME_ZONE_CODE, SHEF_TIME_ZONE_ID, SHEF_TIME_ZONE_DESC)
 Values
   (1, 'UTC', 'Universal Coordinated Time');
COMMIT;
--------------------------------------------------------------------------------
-------------------------
-- AT_DATA_STREAM_ID table.
-- 

CREATE TABLE AT_DATA_STREAM_ID
(
  DATA_STREAM_CODE  NUMBER,
  DB_OFFICE_CODE    NUMBER                      NOT NULL,
  DATA_STREAM_ID    VARCHAR2(16 BYTE)           NOT NULL,
  DATA_STREAM_DESC  VARCHAR2(128 BYTE),
  ACTIVE_FLAG       VARCHAR2(1 BYTE)
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX AT_DATA_STREAM_ID_PK ON AT_DATA_STREAM_ID
(DATA_STREAM_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX AT_DATA_STREAM_ID_U01 ON AT_DATA_STREAM_ID
(DATA_STREAM_ID, DB_OFFICE_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE AT_DATA_STREAM_ID ADD (
  CONSTRAINT AT_DATA_STREAM_ID_PK
 PRIMARY KEY
 (DATA_STREAM_CODE)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ))
/

ALTER TABLE AT_DATA_STREAM_ID ADD (
  CONSTRAINT AT_DATA_STREAM_ID_U01
 UNIQUE (DATA_STREAM_ID, DB_OFFICE_CODE)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ))
/


ALTER TABLE AT_DATA_STREAM_ID ADD (
  CONSTRAINT AT_DATA_STREAM_ID_R01 
 FOREIGN KEY (DB_OFFICE_CODE) 
 REFERENCES CWMS_OFFICE (OFFICE_CODE))
/

--------------------------------------------------------------------------------
CREATE TABLE AT_SHEF_DECODE
(
  TS_CODE                NUMBER,
  DATA_STREAM_CODE       NUMBER,
  SHEF_PE_CODE           VARCHAR2(2 BYTE)       NOT NULL,
  SHEF_TSE_CODE          VARCHAR2(3 BYTE)       NOT NULL,
  SHEF_DURATION_NUMERIC  VARCHAR2(4 BYTE)       NOT NULL,
  SHEF_UNIT_CODE         NUMBER                 NOT NULL,
  SHEF_TIME_ZONE_CODE    NUMBER,
  DL_TIME                VARCHAR2(1 BYTE),
  LOCATION_CODE          NUMBER                 NOT NULL,
  LOC_GROUP_CODE         NUMBER                 NOT NULL,
  SHEF_DURATION_CODE     VARCHAR2(1 BYTE)       NOT NULL,
  SHEF_LOC_ID            VARCHAR2(128 BYTE)     NOT NULL
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX AT_SHEF_DECODE_PK ON AT_SHEF_DECODE
(TS_CODE, DATA_STREAM_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX AT_SHEF_DECODE_U01 ON AT_SHEF_DECODE
(TS_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX AT_SHEF_DECODE_U03 ON AT_SHEF_DECODE
(DATA_STREAM_CODE, SHEF_LOC_ID, SHEF_PE_CODE, SHEF_TSE_CODE, SHEF_DURATION_NUMERIC)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_PK
 PRIMARY KEY
 (TS_CODE, DATA_STREAM_CODE)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ))
/


ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_R05 
 FOREIGN KEY (SHEF_TIME_ZONE_CODE) 
 REFERENCES CWMS_SHEF_TIME_ZONE (SHEF_TIME_ZONE_CODE))
/

ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_R03 
 FOREIGN KEY (SHEF_UNIT_CODE) 
 REFERENCES CWMS_UNIT (UNIT_CODE))
/

ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_R04 
 FOREIGN KEY (SHEF_DURATION_CODE) 
 REFERENCES CWMS_SHEF_DURATION (SHEF_DURATION_CODE))
/

ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_R02 
 FOREIGN KEY (DATA_STREAM_CODE) 
 REFERENCES AT_DATA_STREAM_ID (DATA_STREAM_CODE) DISABLE)
/

ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_R01 
 FOREIGN KEY (TS_CODE) 
 REFERENCES AT_CWMS_TS_SPEC (TS_CODE))
/


--------------------------------------------------------------------------------
CREATE TABLE AT_SHEF_CRIT_FILE
(
  DATA_STREAM_CODE  NUMBER,
  CREATION_DATE     DATE,
  SHEF_CRIT_FILE    CLOB
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
LOB (SHEF_CRIT_FILE) STORE AS 
      ( TABLESPACE  CWMS_20DATA 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  0
        NOCACHE
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX AT_SHEF_CRIT_FILE_PK ON AT_SHEF_CRIT_FILE
(DATA_STREAM_CODE, CREATION_DATE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE AT_SHEF_CRIT_FILE ADD (
  CONSTRAINT AT_SHEF_CRIT_FILE_PK
 PRIMARY KEY
 (DATA_STREAM_CODE, CREATION_DATE)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ))
/


ALTER TABLE AT_SHEF_CRIT_FILE ADD (
  CONSTRAINT AT_SHEF_CRIT_FILE_R01 
 FOREIGN KEY (DATA_STREAM_CODE) 
 REFERENCES AT_DATA_STREAM_ID (DATA_STREAM_CODE))
/