--******************************
--******************************
--------------------------------

CREATE TABLE CWMS_20.CWMS_TR_TRANSFORMATIONS
(
  TRANSFORM_ID  VARCHAR2(32 BYTE)               NOT NULL,
  DESCRIPTION   VARCHAR2(256 BYTE)              NOT NULL
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_20.CWMS_TR_TRANSFORMATIONS_PK ON CWMS_20.CWMS_TR_TRANSFORMATIONS
(TRANSFORM_ID)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX CWMS_20.CWMS_TR_TRANSFORMATIONS_UI01 ON CWMS_20.CWMS_TR_TRANSFORMATIONS
(UPPER("TRANSFORM_ID"))
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE CWMS_20.CWMS_TR_TRANSFORMATIONS ADD (
  CONSTRAINT CWMS_TR_TRANSFORMATIONS_PK
 PRIMARY KEY
 (TRANSFORM_ID)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/


SET DEFINE OFF;
Insert into CWMS_20.CWMS_TR_TRANSFORMATIONS
   (TRANSFORM_ID, DESCRIPTION)
 Values
   ('Validation', 'Triggers a Validation, if validation criteria.');
Insert into CWMS_20.CWMS_TR_TRANSFORMATIONS
   (TRANSFORM_ID, DESCRIPTION)
 Values
   ('Scaling', 'Applies scaling factors as reflected in y = (x + a) b + c');
Insert into CWMS_20.CWMS_TR_TRANSFORMATIONS
   (TRANSFORM_ID, DESCRIPTION)
 Values
   ('Lookup Table', 'Applies a 1 or 2 parameter lookup table against a dependant variable. Lookup table can either be a single table or a set of tables over time, e.g., a set of stage/flow tables that change over time.');
COMMIT;



--************************
--************************
------------------


CREATE TABLE CWMS_20.AT_TR_TEMPLATE_ID
(
  TEMPLATE_CODE             NUMBER,
  TEMPLATE_ID               VARCHAR2(32 BYTE)   NOT NULL,
  DB_OFFICE_CODE            NUMBER              NOT NULL,
  PRIMARY_INDEP_PARAM_CODE  NUMBER,
  DEP_PARAM_CODE            NUMBER,
  DESCRIPTION               VARCHAR2(132 BYTE),
  SEED_VERSION_SUFFIX       VARCHAR2(32 BYTE)
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_20.AT_TR_TEMPLATE_ID_PK ON CWMS_20.AT_TR_TEMPLATE_ID
(TEMPLATE_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX CWMS_20.AT_TR_TEMPLATE_ID_UQ01 ON CWMS_20.AT_TR_TEMPLATE_ID
(UPPER("TEMPLATE_ID"), DB_OFFICE_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE CWMS_20.AT_TR_TEMPLATE_ID ADD (
  CONSTRAINT AT_TR_TEMPLATE_ID_PK
 PRIMARY KEY
 (TEMPLATE_CODE)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

ALTER TABLE CWMS_20.AT_TR_TEMPLATE_ID ADD (
  CONSTRAINT AT_TR_TEMPLATE_ID_R01 
 FOREIGN KEY (DB_OFFICE_CODE) 
 REFERENCES CWMS_20.CWMS_OFFICE (OFFICE_CODE),
  CONSTRAINT AT_TR_TEMPLATE_ID_R02 
 FOREIGN KEY (PRIMARY_INDEP_PARAM_CODE) 
 REFERENCES CWMS_20.AT_PARAMETER (PARAMETER_CODE),
  CONSTRAINT AT_TR_TEMPLATE_ID_R03 
 FOREIGN KEY (DEP_PARAM_CODE) 
 REFERENCES CWMS_20.AT_PARAMETER (PARAMETER_CODE))
/


--************************
--------------------------
--************************



CREATE TABLE CWMS_20.AT_TR_TEMPLATE_SET
(
  TEMPLATE_CODE          NUMBER,
  SEQUENCE_NO            NUMBER,
  DESCRIPTION            VARCHAR2(132 BYTE),
  STORE_DEP_FLAG         VARCHAR2(1 BYTE),
  UNIT_SYSTEM            VARCHAR2(2 BYTE),
  TRANSFORM_ID           VARCHAR2(32 BYTE),
  LOOKUP_AGENCY_SOURCE   VARCHAR2(32 BYTE),
  LOOKUP_SOURCE_VERSION  VARCHAR2(32 BYTE),
  SCALING_ARG_A          NUMBER,
  SCALING_ARG_B          NUMBER,
  SCALING_ARG_C          NUMBER
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON COLUMN CWMS_20.AT_TR_TEMPLATE_SET.DESCRIPTION IS 'description is of AT_TR_TEMPLATE_SET'
/

COMMENT ON COLUMN CWMS_20.AT_TR_TEMPLATE_SET.STORE_DEP_FLAG IS 'If T, then dependent variable is store to database, else it''s simply available for the next transform.'
/

COMMENT ON COLUMN CWMS_20.AT_TR_TEMPLATE_SET.UNIT_SYSTEM IS 'Either SI or EN or null - null indicates that the computation is not system dependant (which means it will really be done in the SI system).'
/


CREATE UNIQUE INDEX CWMS_20.AT_TR_TEMPLATE_SET_PK ON CWMS_20.AT_TR_TEMPLATE_SET
(TEMPLATE_CODE, SEQUENCE_NO)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE CWMS_20.AT_TR_TEMPLATE_SET ADD (
  CONSTRAINT AT_TR_TEMPLATE_SET_PK
 PRIMARY KEY
 (TEMPLATE_CODE, SEQUENCE_NO)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

ALTER TABLE CWMS_20.AT_TR_TEMPLATE_SET ADD (
  CONSTRAINT AT_TR_TEMPLATE_SET_R01 
 FOREIGN KEY (TEMPLATE_CODE) 
 REFERENCES CWMS_20.AT_TR_TEMPLATE_ID (TEMPLATE_CODE),
  CONSTRAINT AT_TR_TEMPLATE_SET_R02 
 FOREIGN KEY (TRANSFORM_ID) 
 REFERENCES CWMS_20.CWMS_TR_TRANSFORMATIONS (TRANSFORM_ID))
/




--************************
--------------------------
--************************


CREATE TABLE CWMS_20.AT_TR_TS_MASK
(
  TEMPLATE_CODE        NUMBER,
  SEQUENCE_NO          NUMBER,
  VARIABLE_NO          NUMBER,
  LOCATION_CODE        NUMBER,
  PARAMETER_CODE       NUMBER,
  PARAMETER_TYPE_CODE  NUMBER,
  INTERVAL_CODE        NUMBER,
  DURATION_CODE        NUMBER,
  VERSION_MASK         VARCHAR2(42 BYTE)
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_20.AT_TR_TS_MASK_PK ON CWMS_20.AT_TR_TS_MASK
(TEMPLATE_CODE, SEQUENCE_NO, VARIABLE_NO)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE CWMS_20.AT_TR_TS_MASK ADD (
  CONSTRAINT AT_TR_TS_MASK_PK
 PRIMARY KEY
 (TEMPLATE_CODE, SEQUENCE_NO, VARIABLE_NO)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

ALTER TABLE CWMS_20.AT_TR_TS_MASK ADD (
  CONSTRAINT AT_TR_TS_MASK_R01 
 FOREIGN KEY (TEMPLATE_CODE, SEQUENCE_NO) 
 REFERENCES CWMS_20.AT_TR_TEMPLATE_SET (TEMPLATE_CODE,SEQUENCE_NO),
  CONSTRAINT AT_TR_TS_MASK1_R02 
 FOREIGN KEY (LOCATION_CODE) 
 REFERENCES CWMS_20.AT_PHYSICAL_LOCATION (LOCATION_CODE),
  CONSTRAINT AT_TR_TS_MASK1_R03 
 FOREIGN KEY (PARAMETER_CODE) 
 REFERENCES CWMS_20.AT_PARAMETER (PARAMETER_CODE),
  CONSTRAINT AT_TR_TS_MASK1_R04 
 FOREIGN KEY (PARAMETER_TYPE_CODE) 
 REFERENCES CWMS_20.CWMS_PARAMETER_TYPE (PARAMETER_TYPE_CODE),
  CONSTRAINT AT_TR_TS_MASK1_R05 
 FOREIGN KEY (INTERVAL_CODE) 
 REFERENCES CWMS_20.CWMS_INTERVAL (INTERVAL_CODE),
  CONSTRAINT AT_TR_TS_MASK1_R06 
 FOREIGN KEY (DURATION_CODE) 
 REFERENCES CWMS_20.CWMS_DURATION (DURATION_CODE))
/


--************************
--------------------------
--************************


CREATE TABLE CWMS_20.AT_TR_TEMPLATE
(
  TS_CODE_INDEP_1  NUMBER,
  TEMPLATE_CODE    NUMBER,
  ACTIVE_FLAG      VARCHAR2(1 BYTE)             NOT NULL,
  EVENT_TRIGGER    VARCHAR2(32 BYTE)            NOT NULL
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_20.AT_TR_TEMPLATE_PK ON CWMS_20.AT_TR_TEMPLATE
(TS_CODE_INDEP_1, TEMPLATE_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE CWMS_20.AT_TR_TEMPLATE ADD (
  CONSTRAINT AT_TR_TEMPLATE_PK
 PRIMARY KEY
 (TS_CODE_INDEP_1, TEMPLATE_CODE)
    USING INDEX 
    TABLESPACE CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/

ALTER TABLE CWMS_20.AT_TR_TEMPLATE ADD (
  CONSTRAINT AT_TR_TEMPLATE_R01 
 FOREIGN KEY (TEMPLATE_CODE) 
 REFERENCES CWMS_20.AT_TR_TEMPLATE_ID (TEMPLATE_CODE),
  CONSTRAINT AT_TR_TEMPLATE_R02 
 FOREIGN KEY (TS_CODE_INDEP_1) 
 REFERENCES CWMS_20.AT_CWMS_TS_SPEC (TS_CODE))
/

