---------------------------------------------------------
@@cwms/views/av_loc.sql
@@cwms/views/av_log_message.sql
@@cwms/views/av_ts_alias.sql
@@cwms/views/av_ts_grp_assgn.sql
@@cwms/views/av_ts_cat_grp.sql
@@cwms/views/av_loc_lvl_ts_map.sql
@@cwms/views/av_loc_lvl_cur_max_ind.sql
---------------------------------------------------------
COMMIT;
