SET TIME ON
SPOOL drop_at_schema.lst
SELECT SYSDATE FROM DUAL;
SET ECHO ON
SET SERVEROUTPUT ON
BEGIN DBMS_OUTPUT.ENABLE(20000); END;
/

EXEC DBMS_AQADM.STOP_QUEUE(QUEUE_NAME  => 'XCHG_QUEUE');
EXEC DBMS_AQADM.DROP_QUEUE(QUEUE_NAME  => 'XCHG_QUEUE');
EXEC DBMS_AQADM.DROP_QUEUE_TABLE(QUEUE_TABLE  => 'XCHG_QUEUE_TABLE');
COMMIT;

DROP TABLE AT_XCHG_TS_INFO_1;
COMMIT;

DROP TABLE AT_XCHG_TS_INFO_2;
COMMIT;

DROP TABLE AT_DSS_RATING_XCHG_MAP;
COMMIT;

DROP TABLE AT_DSS_TS_XCHG_MAP;
COMMIT;

DROP TABLE AT_DSS_XCHG_SET;
COMMIT;

DROP TABLE AT_DSS_TS_XCHG_SPEC;
COMMIT;

DROP TABLE AT_DSS_TS_SPEC;
COMMIT;

DROP TABLE AT_DSS_FILE;
COMMIT;

DROP TABLE AT_UNIT_ALIAS;
COMMIT;

DROP TABLE AT_TS_RATING_SPEC;
COMMIT;

DROP TABLE AT_RATING_TS_SPEC;
COMMIT;

DROP TABLE RATINGS_LOG;
COMMIT;

DROP TABLE AT_DSS_RATING_XCHG_SPEC;
COMMIT;

DROP TABLE AT_RATING_SPEC;
COMMIT;

DROP TABLE AT_DSS_RATING_SPEC;
COMMIT;

DROP TABLE AT_TSV_2002;
COMMIT;

DROP TABLE AT_TSV_2003;
COMMIT;

DROP TABLE AT_TSV_2004;
COMMIT;

DROP TABLE AT_TSV_2005;
COMMIT;

DROP TABLE AT_CWMS_TS_SPEC;
COMMIT;

DROP TABLE AT_SOURCE_NAME;
COMMIT;

DROP TABLE AT_GAGE_LOCATION;
COMMIT;

DROP TABLE AT_GAGE_ID;
COMMIT;

DROP TABLE AT_PHYSICAL_LOCATION;
COMMIT;

DROP TABLE AT_CWMS_NAME;
COMMIT;

DROP TABLE AT_SEC_USER_OFFICE;
COMMIT;

-- DROP SEQUENCE SEQ_TSS;
-- DROP SEQUENCE SEQ_LOCA;
-- DROP SEQUENCE SEQ_CWMS;
-- DROP SEQUENCE SEQ_GAGE_ID;
-- DROP SEQUENCE SEQ_XCHG;
COMMIT;

SPOOL OFF
SET ECHO OFF
SET TIME OFF


