DROP TRIGGER CWMS_20.ST_LOG_MESSAGE;
DROP TRIGGER CWMS_20.ST_LOG_MESSAGE_PROPERTIES;
DROP TRIGGER CWMS_20.ST_APPLICATION_LOGIN;
DROP TRIGGER CWMS_20.ST_APPLICATION_SESSION;
CREATE OR REPLACE TRIGGER ST_VIRTUAL_LOCATION_LEVEL BEFORE DELETE OR INSERT OR UPDATE
              ON AT_VIRTUAL_LOCATION_LEVEL REFERENCING NEW AS NEW OLD AS OLD
DECLARE

             l_priv   VARCHAR2 (16);
             BEGIN
             SELECT SYS_CONTEXT ('CWMS_ENV', 'CWMS_PRIVILEGE') INTO l_priv FROM DUAL;
             IF ((l_priv is NULL OR l_priv <> 'CAN_WRITE') AND user NOT IN ('SYS', 'CWMS_20'))
             THEN

               CWMS_20.CWMS_ERR.RAISE('NO_WRITE_PRIVILEGE');

             END IF;
           END;
/

CREATE OR REPLACE TRIGGER ST_VLOC_LVL_CONSTITUENT BEFORE DELETE OR INSERT OR UPDATE
              ON AT_VLOC_LVL_CONSTITUENT REFERENCING NEW AS NEW OLD AS OLD
DECLARE

             l_priv   VARCHAR2 (16);
             BEGIN
             SELECT SYS_CONTEXT ('CWMS_ENV', 'CWMS_PRIVILEGE') INTO l_priv FROM DUAL;
             IF ((l_priv is NULL OR l_priv <> 'CAN_WRITE') AND user NOT IN ('SYS', 'CWMS_20'))
             THEN

               CWMS_20.CWMS_ERR.RAISE('NO_WRITE_PRIVILEGE');

             END IF;
           END;
/
