CREATE OR REPLACE PACKAGE CWMS_20.cwms_crypt
AS
    FUNCTION ENCRYPT (val VARCHAR2)
        RETURN VARCHAR2;

    FUNCTION DECRYPT (val VARCHAR2)
        RETURN VARCHAR2;
END cwms_crypt;
/

SHOW error;
