exec &STREAMS_USER..extended_datatype_support.remove_tables('&CWMS_SCHEMA..AT_GEOGRAPHIC_LOCATION');
DROP SEQUENCE &STREAMS_USER..STREAMS$_EDS_FNAME_SEQNO;
DROP SEQUENCE &STREAMS_USER..STREAMS$_EDS_HANDLER_SEQNO;
DROP TABLE &STREAMS_USER..EDS_DML_HANDLERS;
DROP TABLE &STREAMS_USER..EDS_DML_TRIGGERS;
DROP TABLE &STREAMS_USER..EDS_MATERIALIZED_VIEWS;
DROP TABLE &STREAMS_USER..EDS_SCRIPT_NAMES;
DROP TABLE &STREAMS_USER..EDS_SHADOW_TABLES;
DROP TABLE &STREAMS_USER..EDS_SUPPORTED_TABLES;
DROP TABLE &STREAMS_USER..EDS_TABLE_RULES;


DROP VIEW &STREAMS_USER..EDS_STREAMS_UNSUPPORTED;
DROP VIEW &STREAMS_USER..EDS_SUPPORTED
DROP VIEW &STREAMS_USER..EDS_UNSUPPORTED_COLUMNS
DROP VIEW &STREAMS_USER..EDS_UNSUPPORTED_SCHEMAS

DROP PACKAGE &STREAMS_USER..extended_datatype_support;
BEGIN
   FOR c IN (SELECT script_id
               FROM dba_recoverable_script
              WHERE invoking_package_owner = '&streams_user')
   LOOP
      DBMS_STREAMS_ADM.recover_operation (c.script_id, 'PURGE');
   END LOOP;
END;
/
