REM INSERTING into CWMS_20.CWMS_STATE
Insert into CWMS_20.CWMS_STATE (STATE_CODE,STATE_INITIAL,NAME,NATION_CODE) values (101,'UC','Shared by USA and Canada','ZZ');
Insert into CWMS_20.CWMS_STATE (STATE_CODE,STATE_INITIAL,NAME,NATION_CODE) values (102,'UM','Shared by USA and Mexico','ZZ');
