---------------
-- AV_RATING --
---------------

insert into at_clob values (cwms_seq.nextval, 53, '/VIEWDOCS/AV_VIRTUAL_RATING', null,
'
/**
 * Displays information on virtual ratings
 *
 * @since CWMS 2.2
 *
 * @field office_id           The office that owns the virtual rating
 * @field rating_spec         The rating specification of the virtual rating
 * @field connections         A text string specifying how the source ratings are connected to form the virtual rating
 * @field position            The position of this source rating within the virtual rating
 * @field source_rating       The rating specification or mathematical expression for this source rating 
 * @field units               The units expected and generated by this source rating
 * @field virtual_rating_code The unique numeric code identifying the virutual rating in the database
 * @field rating_spec_code    The unique numeric code identifying the rating specification in the database
 */
');
create or replace force view av_virtual_rating(
   office_id,
   rating_spec,
   connections,
   position,
   source_rating,
   units,
   virtual_rating_code,
   rating_spec_code)
as
     select rs1.office_id as office_id,
            rs1.location_id || '.' || rs1.template_id || '.' || rs1.version as rating_spec,
            connections,
            vre.position,
            case
               when vre.rating_spec_code is null then vre.rating_expression
               else rs2.location_id || '.' || rs2.template_id || '.' || rs2.version
            end
               as source_rating,
            reverse(
               regexp_replace(
                  reverse(
                     cwms_util.join_text(
                        cast(
                           multiset(                        
                                select cwms_util.get_unit_id2(vru.unit_code)
                                  from at_virtual_rating_unit vru
                                 where vru.virtual_rating_element_code = vre.virtual_rating_element_code
                              order by vru.position) as str_tab_t),
                        ',')),
                  ',',
                  ';',
                  1,
                  1))
               as units,
            vr.virtual_rating_code,
            vr.rating_spec_code
       from at_virtual_rating vr,
            at_virtual_rating_element vre,
            table(rating_spec_tab_t(rating_spec_t(vr.rating_spec_code))) rs1,
            table(rating_spec_tab_t(rating_spec_t(nvl(vre.rating_spec_code, vr.rating_spec_code)))) rs2
      where vre.virtual_rating_code = vr.virtual_rating_code;

CREATE OR REPLACE PUBLIC SYNONYM CWMS_V_VIRTUAL_RATING FOR AV_VIRTUAL_RATING;
