plugins {
    id 'database.deps-conventions'
    id 'database.java-conventions'
    id 'application'
}

configurations {
    compile
    flywayMigration
    utplsql
}

application {
    mainClass = 'cwms.Migration'
}

tasks.withType(JavaExec) {
    args "build/flyway.conf"
}

dependencies {
    implementation(libs.org.flyway.core)
    implementation(libs.oracle.jdbc.driver)
    implementation(libs.org.flyway.database.oracle)
    implementation(libs.net.objecthunter.exp4j)
    implementation(libs.bundles.jackson)
    implementation(libs.org.apache.commons.io)
    implementation(libs.org.opendcs.java.algebra.system)

    compile(libs.org.flyway.core)
    
    flywayMigration sourceSets.main.runtimeClasspath

    utplsql 'org.utplsql:utplsql:3.1.10@zip'
}

def testMigrationCode = tasks.register("testMigrationCode", Test) {
    dependsOn compileJava
    dependsOn compileTestJava
    useJUnitPlatform()
}

test.dependsOn testMigrationCode
