CREATE USER CWMS_DBA
  identified by values 'FEDCCA9876543210'
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK
/
  -- 1 Role for CWMS_DBA 
  GRANT CONNECT TO CWMS_DBA
/
GRANT "MGMT_USER" TO "CWMS_DBA"
/
  ALTER USER CWMS_DBA DEFAULT ROLE ALL
/
  -- 4 System Privileges for CWMS_DBA 
  GRANT GRANT ANY ROLE TO CWMS_DBA
/
  GRANT ALTER USER TO CWMS_DBA
/
  GRANT CREATE USER TO CWMS_DBA
/
  GRANT CREATE SESSION TO "CWMS_DBA" WITH ADMIN OPTION
/
  GRANT DROP USER TO "CWMS_DBA"
/
  GRANT SELECT ANY DICTIONARY TO "CWMS_DBA"
/
