SET DEFINE OFF;
CREATE ROLE CWMS_DEV NOT IDENTIFIED;

GRANT CREATE JOB TO CWMS_DEV;
GRANT ANALYZE ANY TO CWMS_DEV;
GRANT BECOME USER TO CWMS_DEV;
GRANT CREATE TYPE TO CWMS_DEV;
GRANT CREATE VIEW TO CWMS_DEV;
GRANT CREATE TABLE TO CWMS_DEV;
GRANT DROP ANY TYPE TO CWMS_DEV;
GRANT DROP ANY VIEW TO CWMS_DEV;
GRANT ALTER ANY TYPE TO CWMS_DEV;
GRANT ALTER DATABASE TO CWMS_DEV;
GRANT CREATE ANY JOB TO CWMS_DEV;
GRANT CREATE LIBRARY TO CWMS_DEV;
GRANT CREATE SESSION TO CWMS_DEV;
GRANT CREATE SYNONYM TO CWMS_DEV;
GRANT CREATE TRIGGER TO CWMS_DEV;
GRANT DROP ANY INDEX TO CWMS_DEV;
GRANT DROP ANY TABLE TO CWMS_DEV;
GRANT ALTER ANY INDEX TO CWMS_DEV;
GRANT ALTER ANY TABLE TO CWMS_DEV;
GRANT CREATE ANY TYPE TO CWMS_DEV;
GRANT CREATE ANY VIEW TO CWMS_DEV;
GRANT CREATE SEQUENCE TO CWMS_DEV;
GRANT DROP TABLESPACE TO CWMS_DEV;
GRANT ALTER TABLESPACE TO CWMS_DEV;
GRANT CREATE ANY INDEX TO CWMS_DEV;
GRANT CREATE ANY TABLE TO CWMS_DEV;
GRANT CREATE INDEXTYPE TO CWMS_DEV;
GRANT CREATE PROCEDURE TO CWMS_DEV;
GRANT DELETE ANY TABLE TO CWMS_DEV;
GRANT DROP ANY TRIGGER TO CWMS_DEV;
GRANT EXECUTE ANY TYPE TO CWMS_DEV;
GRANT INSERT ANY TABLE TO CWMS_DEV;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'CWMS_DEV',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE SCHEDULER TO CWMS_DEV;
GRANT SELECT ANY TABLE TO CWMS_DEV;
GRANT UPDATE ANY TABLE TO CWMS_DEV;
GRANT ALTER ANY TRIGGER TO CWMS_DEV;
GRANT COMMENT ANY TABLE TO CWMS_DEV;
GRANT CREATE TABLESPACE TO CWMS_DEV;
GRANT DROP ANY SEQUENCE TO CWMS_DEV;
GRANT EXECUTE ANY CLASS TO CWMS_DEV;
GRANT MANAGE TABLESPACE TO CWMS_DEV;
GRANT ALTER ANY SEQUENCE TO CWMS_DEV;
GRANT CREATE ANY LIBRARY TO CWMS_DEV;
GRANT CREATE ANY SYNONYM TO CWMS_DEV;
GRANT CREATE ANY TRIGGER TO CWMS_DEV;
GRANT DROP ANY INDEXTYPE TO CWMS_DEV;
GRANT DROP ANY PROCEDURE TO CWMS_DEV;
GRANT ALTER ANY INDEXTYPE TO CWMS_DEV;
GRANT ALTER ANY PROCEDURE TO CWMS_DEV;
GRANT ALTER RESOURCE COST TO CWMS_DEV;
GRANT CREATE ANY SEQUENCE TO CWMS_DEV;
GRANT CREATE EXTERNAL JOB TO CWMS_DEV;
GRANT DEBUG ANY PROCEDURE TO CWMS_DEV;
GRANT DROP PUBLIC SYNONYM TO CWMS_DEV;
GRANT SELECT ANY SEQUENCE TO CWMS_DEV;
GRANT CREATE ANY DIRECTORY TO CWMS_DEV;
GRANT CREATE ANY INDEXTYPE TO CWMS_DEV;
GRANT CREATE ANY PROCEDURE TO CWMS_DEV;
GRANT EXPORT FULL DATABASE TO CWMS_DEV;
GRANT IMPORT FULL DATABASE TO CWMS_DEV;
GRANT DEBUG CONNECT SESSION TO CWMS_DEV;
GRANT EXECUTE ANY INDEXTYPE TO CWMS_DEV;
GRANT EXECUTE ANY PROCEDURE TO CWMS_DEV;
GRANT SELECT ANY DICTIONARY TO CWMS_DEV;
GRANT ANALYZE ANY DICTIONARY TO CWMS_DEV;
GRANT CREATE MATERIALIZED VIEW TO CWMS_DEV;
GRANT DROP ANY MATERIALIZED VIEW TO CWMS_DEV;
GRANT ALTER ANY MATERIALIZED VIEW TO CWMS_DEV;
GRANT CREATE ANY MATERIALIZED VIEW TO CWMS_DEV;
GRANT CONNECT TO CWMS_DEV;


