CREATE USER CWMS_20
  IDENTIFIED BY VALUES 'E6DFE7B643C8C891'
  DEFAULT TABLESPACE CWMS_20DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
-- 4 Roles for CWMS_20 
GRANT AQ_ADMINISTRATOR_ROLE TO CWMS_20;
GRANT CONNECT TO CWMS_20;
GRANT AQ_USER_ROLE TO CWMS_20;
GRANT CWMS_DEV TO CWMS_20;
ALTER USER CWMS_20 DEFAULT ROLE ALL;

-- 19 System Privileges for CWMS_20 
GRANT CREATE ANY CONTEXT TO CWMS_20;
GRANT CREATE TABLE TO CWMS_20;
GRANT CREATE LIBRARY TO CWMS_20;
GRANT CREATE JOB TO CWMS_20;
BEGIN
  SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
    PRIVILEGE    => 'DEQUEUE_ANY',
    GRANTEE      => 'CWMS_20',
    ADMIN_OPTION => FALSE);
END;
/
GRANT CREATE PROCEDURE TO CWMS_20;
GRANT CREATE VIEW TO CWMS_20;
GRANT CREATE TRIGGER TO CWMS_20;
GRANT CREATE DATABASE LINK TO CWMS_20;
GRANT CREATE CLUSTER TO CWMS_20;
GRANT CREATE OPERATOR TO CWMS_20;
GRANT CREATE SEQUENCE TO CWMS_20;
GRANT SELECT ANY DICTIONARY TO CWMS_20;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'CWMS_20',
  ADMIN_OPTION => FALSE);
END;
/
GRANT CREATE INDEXTYPE TO CWMS_20;
GRANT CREATE TYPE TO CWMS_20;
GRANT CREATE SYNONYM TO CWMS_20;
GRANT CREATE DIMENSION TO CWMS_20;
GRANT CREATE MATERIALIZED VIEW TO CWMS_20;

-- 4 Tablespace Quotas for CWMS_20 
ALTER USER CWMS_20 QUOTA UNLIMITED ON CWMS_20AT_DATA;
ALTER USER CWMS_20 QUOTA UNLIMITED ON CWMS_20DATA;
ALTER USER CWMS_20 QUOTA UNLIMITED ON CWMS_20_TSV;

-- 12 Object Privileges for CWMS_20 
GRANT EXECUTE ON  CTXSYS.CTX_DDL TO CWMS_20;
GRANT EXECUTE ON  CTXSYS.CTX_DOC TO CWMS_20;
GRANT EXECUTE ON  SYS.DBMS_AQ TO CWMS_20;
GRANT EXECUTE ON  SYS.DBMS_AQ_BQVIEW TO CWMS_20;
GRANT EXECUTE ON  SYS.DBMS_LOCK TO CWMS_20;
GRANT EXECUTE ON  SYS.DBMS_RLS TO CWMS_20;
GRANT SELECT ON  SYS.V_$LATCH TO CWMS_20;
GRANT SELECT ON  SYS.V_$MYSTAT TO CWMS_20;
GRANT SELECT ON  SYS.V_$STATNAME TO CWMS_20;
GRANT SELECT ON  SYS.V_$TIMER TO CWMS_20;
GRANT SELECT ON  TOAD.TOAD_RESTRICTIONS TO CWMS_20 WITH GRANT OPTION;
GRANT DELETE, INSERT ON  TOAD.TOAD_RESTRICTIONS TO CWMS_20;


