CREATE USER CWMS_DBA no authentication
  DEFAULT TABLESPACE SYSTEM
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK
/
  -- This grants connect role 
  GRANT CREATE SESSION TO CWMS_DBA
/
  GRANT SET CONTAINER TO CWMS_DBA
/
-- This role seems to be unnecessary and is causing problem on M3000 installations
-- GRANT "MGMT_USER" TO "CWMS_DBA"
/
  ALTER USER CWMS_DBA DEFAULT ROLE ALL
/
  -- 4 System Privileges for CWMS_DBA 
  GRANT ALTER USER TO CWMS_DBA
/
  GRANT CREATE USER TO CWMS_DBA
/
  GRANT CREATE SESSION TO "CWMS_DBA" WITH ADMIN OPTION
/
  GRANT DROP USER TO "CWMS_DBA"
/
  GRANT SELECT ANY DICTIONARY TO "CWMS_DBA"
/
