/* Formatted on 5/1/2014 12:34:13 PM (QP5 v5.215.12089.38647) */
CREATE TABLE AT_A2W_TS_CODES_BY_LOC
(
   LOCATION_ID            VARCHAR2 (199 BYTE),
   DB_OFFICE_ID           VARCHAR2 (5 BYTE),
   TS_CODE_ELEV           NUMBER,
   TS_CODE_PRECIP         NUMBER,
   TS_CODE_STAGE          NUMBER,
   TS_CODE_INFLOW         NUMBER,
   TS_CODE_OUTFLOW        NUMBER,
   DATE_REFRESHED         DATE NOT NULL,
   TS_CODE_STOR_FLOOD     NUMBER,
   NOTES                  CLOB,
   DISPLAY_FLAG           VARCHAR2 (1 BYTE) DEFAULT 'F' NOT NULL,
   NUM_TS_CODES           NUMBER DEFAULT 0 NOT NULL,
   TS_CODE_STOR_DROUGHT   NUMBER,
   LAKE_SUMMARY_TF        VARCHAR2 (1 BYTE) DEFAULT 'F' NOT NULL,
   TS_CODE_SUR_RELEASE    NUMBER
)
LOB (NOTES) STORE AS
   (TABLESPACE CWMS_20AT_DATA
    ENABLE STORAGE IN ROW
    CHUNK 8192
    RETENTION
    NOCACHE LOGGING
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             BUFFER_POOL DEFAULT
             FLASH_CACHE DEFAULT
             CELL_FLASH_CACHE DEFAULT))
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/
COMMENT ON TABLE AT_A2W_TS_CODES_BY_LOC IS
   'The AT_A2W_TS_CODES_BY_LOC table stores the WM choice of TS Codes representing a locations elevation, precipitation, stage, inflow, outflow, flood storage, drought storage, and surcharge releases. The TS Codes establish a 1:1 relationship between location and display in various nationwide/public reports. Additional details are in the column comments/'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.LOCATION_ID IS
   'The Location this record applies to'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.DB_OFFICE_ID IS
   'The office that the record is owned by'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_ELEV IS
   'The TS Code showing elevation (projects)'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_PRECIP IS
   'The TS Code showing precipitation at the project'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_STAGE IS
   'The TS Code showing stage (stream gages)'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_INFLOW IS
   'The TS Code showing inflow into the reservoir'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_OUTFLOW IS
   'The TS Code showing outflow through the project'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.DATE_REFRESHED IS
   'The date this record was created/last updated'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_STOR_FLOOD IS
   'The TS Code showing calculated flood storage'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.NOTES IS
   'Any notes generated by the initial data load or the WM through CMA'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.DISPLAY_FLAG IS
   'Flag recording the WM choice to display this location in a hierarchy'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.NUM_TS_CODES IS
   'Calculated count of TS Codes (+1 ea. for elev,precip,stage, etc.)'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_STOR_DROUGHT IS
   'The TS Code showing calculated drought/conservation storage storage'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.LAKE_SUMMARY_TF IS
   'The flag recording if this location should be in the lake summary report'
/
COMMENT ON COLUMN AT_A2W_TS_CODES_BY_LOC.TS_CODE_SUR_RELEASE IS
   'The TS Code showing Surchage Releases (flow)'
/
CREATE INDEX A2W_COUNTS_IDX
   ON AT_A2W_TS_CODES_BY_LOC (LOCATION_ID, DB_OFFICE_ID, DISPLAY_FLAG)
   LOGGING
   NOPARALLEL
/
CREATE UNIQUE INDEX AT_A2W_TS_CODES_BY_LOC_PK
   ON AT_A2W_TS_CODES_BY_LOC (LOCATION_ID, DB_OFFICE_ID)
   LOGGING
   NOPARALLEL
/
