--
-- AT_DATA_STREAM_ID  (Table) 
--
--  Dependencies: 
--   CWMS_OFFICE (Table)
--
--   Row count:10
CREATE TABLE AT_DATA_STREAM_ID
(
  DATA_STREAM_CODE       NUMBER,
  DB_OFFICE_CODE         NUMBER                 NOT NULL,
  DATA_STREAM_ID         VARCHAR2(16 BYTE)      NOT NULL,
  DATA_STREAM_DESC       VARCHAR2(128 BYTE),
  ACTIVE_FLAG            VARCHAR2(1 BYTE),
  DELETE_DATE            DATE,
  DATA_STREAM_MGT_STYLE  VARCHAR2(32 BYTE),
  UPDATE_CRIT_FILE       VARCHAR2(1 BYTE)
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- AT_DATA_STREAM_ID_PK  (Index) 
--
--  Dependencies: 
--   AT_DATA_STREAM_ID (Table)
--
CREATE UNIQUE INDEX AT_DATA_STREAM_ID_PK ON AT_DATA_STREAM_ID
(DATA_STREAM_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- AT_DATA_STREAM_ID_U02  (Index) 
--
--  Dependencies: 
--   AT_DATA_STREAM_ID (Table)
--
CREATE UNIQUE INDEX AT_DATA_STREAM_ID_U02 ON AT_DATA_STREAM_ID
(DATA_STREAM_ID, DB_OFFICE_CODE, DELETE_DATE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table AT_DATA_STREAM_ID 
-- 
ALTER TABLE AT_DATA_STREAM_ID ADD (
  CONSTRAINT AT_DATA_STREAM_ID_PK
  PRIMARY KEY
  (DATA_STREAM_CODE)
  USING INDEX AT_DATA_STREAM_ID_PK)
/

-- 
-- Foreign Key Constraints for Table AT_DATA_STREAM_ID 
-- 
ALTER TABLE AT_DATA_STREAM_ID ADD (
  CONSTRAINT AT_DATA_STREAM_ID_R01 
  FOREIGN KEY (DB_OFFICE_CODE) 
  REFERENCES CWMS_OFFICE (OFFICE_CODE))
/