--
-- AT_SHEF_DECODE  (Table) 
--
--  Dependencies: 
--   CWMS_SHEF_TIME_ZONE (Table)
--   CWMS_UNIT (Table)
--   CWMS_SHEF_DURATION (Table)
--   AT_DATA_STREAM_ID (Table)
--   AT_CWMS_TS_SPEC (Table)
--   AT_DATA_FEED_ID (Table)
--
--   Row count:4501
CREATE TABLE AT_SHEF_DECODE
(
  TS_CODE                NUMBER,
  DATA_STREAM_CODE       NUMBER,
  SHEF_PE_CODE           VARCHAR2(2 BYTE)       NOT NULL,
  SHEF_TSE_CODE          VARCHAR2(3 BYTE)       NOT NULL,
  SHEF_DURATION_NUMERIC  VARCHAR2(4 BYTE)       NOT NULL,
  SHEF_UNIT_CODE         NUMBER                 NOT NULL,
  SHEF_TIME_ZONE_CODE    NUMBER,
  DL_TIME                VARCHAR2(1 BYTE),
  LOCATION_CODE          NUMBER                 NOT NULL,
  LOC_GROUP_CODE         NUMBER                 NOT NULL,
  SHEF_DURATION_CODE     VARCHAR2(1 BYTE)       NOT NULL,
  SHEF_LOC_ID            VARCHAR2(128 BYTE)     NOT NULL,
  DATA_FEED_CODE         NUMBER,
  IGNORE_SHEF_SPEC       VARCHAR2(1 BYTE)       NOT NULL
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- AT_SHEF_DECODE_PK  (Index) 
--
--  Dependencies: 
--   AT_SHEF_DECODE (Table)
--
CREATE UNIQUE INDEX AT_SHEF_DECODE_PK ON AT_SHEF_DECODE
(TS_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- AT_SHEF_DECODE_U03  (Index) 
--
--  Dependencies: 
--   AT_SHEF_DECODE (Table)
--
CREATE UNIQUE INDEX AT_SHEF_DECODE_U03 ON AT_SHEF_DECODE
(DATA_STREAM_CODE, SHEF_LOC_ID, SHEF_PE_CODE, SHEF_TSE_CODE, SHEF_DURATION_NUMERIC, 
DATA_FEED_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table AT_SHEF_DECODE 
-- 
ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_C01
  CHECK (data_stream_code is not null or data_feed_code is not null),
  CONSTRAINT AT_SHEF_DECODE_PK
  PRIMARY KEY
  (TS_CODE)
  USING INDEX AT_SHEF_DECODE_PK)
/

-- 
-- Foreign Key Constraints for Table AT_SHEF_DECODE 
-- 
ALTER TABLE AT_SHEF_DECODE ADD (
  CONSTRAINT AT_SHEF_DECODE_R01 
  FOREIGN KEY (TS_CODE) 
  REFERENCES AT_CWMS_TS_SPEC (TS_CODE),
  CONSTRAINT AT_SHEF_DECODE_R02 
  FOREIGN KEY (DATA_STREAM_CODE) 
  REFERENCES AT_DATA_STREAM_ID (DATA_STREAM_CODE)  DISABLE,
  CONSTRAINT AT_SHEF_DECODE_R03 
  FOREIGN KEY (SHEF_UNIT_CODE) 
  REFERENCES CWMS_UNIT (UNIT_CODE),
  CONSTRAINT AT_SHEF_DECODE_R04 
  FOREIGN KEY (SHEF_DURATION_CODE) 
  REFERENCES CWMS_SHEF_DURATION (SHEF_DURATION_CODE),
  CONSTRAINT AT_SHEF_DECODE_R05 
  FOREIGN KEY (SHEF_TIME_ZONE_CODE) 
  REFERENCES CWMS_SHEF_TIME_ZONE (SHEF_TIME_ZONE_CODE),
  CONSTRAINT AT_SHEF_DECODE_R06 
  FOREIGN KEY (DATA_FEED_CODE) 
  REFERENCES AT_DATA_FEED_ID (DATA_FEED_CODE))
/
