--
-- AT_SHEF_CRIT_FILE  (Table) 
--
--  Dependencies: 
--   AT_SHEF_CRIT_FILE_REC (Table)
--
CREATE TABLE AT_SHEF_CRIT_FILE
(
  CRIT_FILE_CODE  NUMBER,
  SHEF_CRIT_LINE  VARCHAR2(2000 BYTE)
)
TABLESPACE CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- AT_SHEF_CRIT_FILE_NI01  (Index) 
--
--  Dependencies: 
--   AT_SHEF_CRIT_FILE (Table)
--
CREATE INDEX AT_SHEF_CRIT_FILE_NI01 ON AT_SHEF_CRIT_FILE
(CRIT_FILE_CODE)
LOGGING
TABLESPACE CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Foreign Key Constraints for Table AT_SHEF_CRIT_FILE 
-- 
ALTER TABLE AT_SHEF_CRIT_FILE ADD (
  CONSTRAINT AT_SHEF_CRIT_FILE_R01 
  FOREIGN KEY (CRIT_FILE_CODE) 
  REFERENCES AT_SHEF_CRIT_FILE_REC (CRIT_FILE_CODE))
/
