CREATE TABLE AT_SHEF_PE_CODES
(
  DB_OFFICE_CODE       NUMBER                   NOT NULL,
  SHEF_PE_CODE         VARCHAR2(2 BYTE)         NOT NULL,
  ID_CODE              NUMBER                   NOT NULL,
  SHEF_TSE_CODE        VARCHAR2(3 BYTE),
  SHEF_DURATION_CODE   VARCHAR2(1 BYTE),
  SHEF_REQ_SEND_CODE   VARCHAR2(7 BYTE),
  UNIT_CODE_EN         NUMBER,
  UNIT_CODE_SI         NUMBER,
  PARAMETER_CODE       NUMBER,
  PARAMETER_TYPE_CODE  NUMBER,
  DESCRIPTION          VARCHAR2(256 BYTE),
  NOTES                VARCHAR2(258 BYTE)
)
tablespace CWMS_20DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX AT_SHEF_PE_CODES_IDX02 ON AT_SHEF_PE_CODES
(ID_CODE)
LOGGING
tablespace CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX AT_SHEF_PE_CODES_IDX03 ON AT_SHEF_PE_CODES
(DB_OFFICE_CODE, SHEF_PE_CODE, SHEF_TSE_CODE, SHEF_DURATION_CODE, SHEF_REQ_SEND_CODE, 
UNIT_CODE_EN, UNIT_CODE_SI, PARAMETER_CODE, PARAMETER_TYPE_CODE)
LOGGING
tablespace CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX AT_SHEF_PE_CODES_IDX1 ON AT_SHEF_PE_CODES
(DB_OFFICE_CODE, SHEF_PE_CODE, SHEF_TSE_CODE, SHEF_DURATION_CODE, SHEF_REQ_SEND_CODE, 
UNIT_CODE_EN, UNIT_CODE_SI, PARAMETER_CODE, PARAMETER_TYPE_CODE, UPPER("DESCRIPTION"), 
UPPER("NOTES"))
LOGGING
tablespace CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE UNIQUE INDEX AT_SHEF_PE_CODES_PK ON AT_SHEF_PE_CODES
(SHEF_PE_CODE, DB_OFFICE_CODE, ID_CODE)
LOGGING
tablespace CWMS_20DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


CREATE OR REPLACE TRIGGER at_shef_pe_codes_trg01
   BEFORE INSERT OR UPDATE OF shef_pe_code
   ON AT_SHEF_PE_CODES    REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   :NEW.shef_pe_code := UPPER (:NEW.shef_pe_code);
END;
/


CREATE OR REPLACE TRIGGER at_shef_pe_codes_trg03
   BEFORE INSERT OR UPDATE OF shef_duration_code
   ON AT_SHEF_PE_CODES    REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   :NEW.shef_duration_code := UPPER (:NEW.shef_duration_code);
END;
/


CREATE OR REPLACE TRIGGER at_shef_pe_codes_trg04
   BEFORE INSERT OR UPDATE OF shef_req_send_code
   ON AT_SHEF_PE_CODES    REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   :NEW.shef_req_send_code := UPPER (:NEW.shef_req_send_code);
END;
/


CREATE OR REPLACE TRIGGER at_shef_pe_codes_trg02
   BEFORE INSERT OR UPDATE OF shef_tse_code
   ON AT_SHEF_PE_CODES    REFERENCING NEW AS NEW OLD AS OLD
   FOR EACH ROW
DECLARE
BEGIN
   :NEW.shef_tse_code := UPPER (:NEW.shef_tse_code);
END;
/


ALTER TABLE AT_SHEF_PE_CODES ADD (
  CONSTRAINT AT_SHEF_PE_CODES_PK
 PRIMARY KEY
 (DB_OFFICE_CODE, SHEF_PE_CODE, ID_CODE)
    USING INDEX 
    tablespace CWMS_20DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/