CREATE TABLE CWMS_STATION_USGS
(
   "AGENCY_CD"          VARCHAR2 (1999 BYTE) NOT NULL ENABLE,
   "STATION_ID"         VARCHAR2 (1999 BYTE) NOT NULL ENABLE,
   "STATION_NAME"       VARCHAR2 (1999 BYTE),
   "SITE_TYPE_CODE"     VARCHAR2 (10 BYTE),
   "LAT"                NUMBER,
   "LON"                NUMBER,
   "COORD_ACY_CD"       VARCHAR2 (25 BYTE),
   "DATUM_HORIZONTAL"   VARCHAR2 (25 BYTE),
   "ALT_VA"             NUMBER,
   "ALT_ACY_VA"         NUMBER,
   "DATUM_VERTICAL"     VARCHAR2 (25 BYTE),
   "STATE_ABBR"         VARCHAR2 (2 BYTE),
   "SHAPE"              "MDSYS"."SDO_GEOMETRY"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
NOCOMPRESS
LOGGING
STORAGE (INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
TABLESPACE CWMS_20DATA;
