CREATE TABLE CWMS_SHEF_PE_CODES
(
  SHEF_PE_CODE         VARCHAR2(2 BYTE),
  SHEF_TSE_CODE        VARCHAR2(3 BYTE),
  SHEF_DURATION_CODE   VARCHAR2(1 BYTE),
  SHEF_REQ_SEND_CODE   VARCHAR2(7 BYTE),
  UNIT_CODE_EN         NUMBER,
  UNIT_CODE_SI         NUMBER,
  PARAMETER_CODE       NUMBER,
  PARAMETER_TYPE_CODE  NUMBER,
  DESCRIPTION          VARCHAR2(256 BYTE),
  NOTES                VARCHAR2(258 BYTE)
)
tablespace CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_SHEF_PE_CODES_PK ON CWMS_SHEF_PE_CODES
(SHEF_PE_CODE)
LOGGING
tablespace CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


ALTER TABLE CWMS_SHEF_PE_CODES ADD (
  CONSTRAINT CWMS_SHEF_PE_CODES_PK
 PRIMARY KEY
 (SHEF_PE_CODE)
    USING INDEX 
    tablespace CWMS_20AT_DATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ))
/