CREATE TABLE CWMS_NID
(
   "RECORDID"            NUMBER,
   "DAM_NAME"            VARCHAR2 (2000 BYTE),
   "OTHER_DAM_NAME"      VARCHAR2 (2000 BYTE),
   "DAM_FORMER_NAME"     VARCHAR2 (2000 BYTE),
   "STATEID"             VARCHAR2 (1000 BYTE),
   "NIDID"               VARCHAR2 (1000 BYTE),
   "LONGITUDE"           NUMBER,
   "LATITUDE"            NUMBER,
   "SECTION"             VARCHAR2 (1000 BYTE),
   "COUNTY"              VARCHAR2 (1000 BYTE),
   "RIVER"               VARCHAR2 (1000 BYTE),
   "CITY"                VARCHAR2 (1000 BYTE),
   "DISTANCE"            NUMBER,
   "OWNER_NAME"          VARCHAR2 (1000 BYTE),
   "USACE_CRITICAL"      VARCHAR2 (1000 BYTE),
   "OWNER_TYPE"          VARCHAR2 (1000 BYTE),
   "DAM_DESIGNER"        VARCHAR2 (1000 BYTE),
   "PRIVATE_DAM"         VARCHAR2 (1000 BYTE),
   "DAM_TYPE"            VARCHAR2 (1000 BYTE),
   "CORE"                VARCHAR2 (1000 BYTE),
   "FOUNDATION"          VARCHAR2 (1000 BYTE),
   "PURPOSES"            VARCHAR2 (2000 BYTE),
   "YEAR_COMPLETED"      VARCHAR2 (1000 BYTE),
   "YEAR_MODIFIED"       VARCHAR2 (1000 BYTE),
   "DAM_LENGTH"          NUMBER,
   "DAM_HEIGHT"          NUMBER,
   "STRUCTURAL_HEIGHT"   NUMBER,
   "HYDRAULIC_HEIGHT"    NUMBER,
   "NID_HEIGHT"          NUMBER,
   "MAX_DISCHARGE"       NUMBER,
   "MAX_STORAGE"         NUMBER,
   "NORMAL_STORAGE"      NUMBER,
   "NID_STORAGE"         NUMBER,
   "SURFACE_AREA"        NUMBER,
   "DRAINAGE_AREA"       NUMBER,
   "SORT_CATEGORY"       NUMBER,
   "SHAPE"               "MDSYS"."SDO_GEOMETRY"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
NOCOMPRESS
LOGGING
STORAGE (INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
TABLESPACE CWMS_20DATA;
