CREATE TABLE CWMS_OFFICES_GEOLOC
(
   OFFICE_CODE   NUMBER,
   OBJECTID_1    INTEGER NOT NULL,
   OBJECTID      NUMBER (15, 6),
   OFFICE_NAM    VARCHAR2 (254 BYTE),
   ORG_SYMBOL    VARCHAR2 (254 BYTE),
   SHAPE         MDSYS.SDO_GEOMETRY
)
COLUMN SHAPE NOT SUBSTITUTABLE AT ALL LEVELS
VARRAY "SHAPE"."SDO_ELEM_INFO"
   STORE AS LOB (ENABLE STORAGE IN ROW
                 CHUNK 8192
                 RETENTION
                 CACHE LOGGING
                 STORAGE (INITIAL 64 K
                          NEXT 1 M
                          MINEXTENTS 1
                          MAXEXTENTS UNLIMITED
                          PCTINCREASE 0
                          BUFFER_POOL DEFAULT
                          FLASH_CACHE DEFAULT
                          CELL_FLASH_CACHE DEFAULT))
VARRAY "SHAPE"."SDO_ORDINATES"
   STORE AS LOB (ENABLE STORAGE IN ROW
                 CHUNK 8192
                 RETENTION
                 CACHE LOGGING
                 STORAGE (INITIAL 64 K
                          NEXT 1 M
                          MINEXTENTS 1
                          MAXEXTENTS UNLIMITED
                          PCTINCREASE 0
                          BUFFER_POOL DEFAULT
                          FLASH_CACHE DEFAULT
                          CELL_FLASH_CACHE DEFAULT))
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/


CREATE UNIQUE INDEX CWMS_OFFICES_GEOLOC_PK
   ON CWMS_OFFICES_GEOLOC (OFFICE_CODE)
   LOGGING
   NOPARALLEL
/


ALTER TABLE CWMS_OFFICES_GEOLOC ADD (
  CONSTRAINT CWMS_OFFICES_GEOLOC_PK
  PRIMARY KEY
  (OFFICE_CODE)
  USING INDEX CWMS_OFFICES_GEOLOC_PK
  ENABLE VALIDATE)
/

ALTER TABLE CWMS_OFFICES_GEOLOC ADD (
  CONSTRAINT CWMS_OFFICES_GEOLOC_R01
  FOREIGN KEY (OFFICE_CODE)
  REFERENCES CWMS_OFFICE (OFFICE_CODE)
  ENABLE VALIDATE)
/

