CREATE TABLE CWMS_NATION_SP
(
   "OBJECTID"     INTEGER NOT NULL ENABLE,
   "FIPS_CNTRY"   VARCHAR2 (2 BYTE),
   "GMI_CNTRY"    VARCHAR2 (3 BYTE),
   "ISO_2DIGIT"   VARCHAR2 (2 BYTE),
   "ISO_3DIGIT"   VARCHAR2 (3 BYTE),
   "CNTRY_NAME"   VARCHAR2 (40 BYTE),
   "LONG_NAME"    VARCHAR2 (40 BYTE),
   "SOVEREIGN"    VARCHAR2 (40 BYTE),
   "POP_CNTRY"    NUMBER (14, 0),
   "CURR_TYPE"    VARCHAR2 (16 BYTE),
   "CURR_CODE"    VARCHAR2 (4 BYTE),
   "LANDLOCKED"   VARCHAR2 (1 BYTE),
   "SQKM"         NUMBER (13, 2),
   "SQMI"         NUMBER (13, 2),
   "COLOR_MAP"    VARCHAR2 (1 BYTE),
   "SHAPE"        "MDSYS"."SDO_GEOMETRY"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
NOCOMPRESS
LOGGING
STORAGE (INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
TABLESPACE CWMS_20DATA;

ALTER TABLE CWMS_20.CWMS_NATION_SP
 ADD CONSTRAINT CWMS_NATION_SP_U1
  UNIQUE (CNTRY_NAME)
  ENABLE VALIDATE;

