CREATE TABLE CWMS_COUNTY_SP
(
   county_code    NUMBER (10),
   OBJECTID     NUMBER NOT NULL ENABLE,
   STATE        VARCHAR2 (2 BYTE),
   COUNTY       VARCHAR2 (50 BYTE),
   FIPS         VARCHAR2 (5 BYTE),
   SQUARE_MIL   NUMBER,
   SHAPE        "MDSYS"."SDO_GEOMETRY"
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10
PCTUSED 40
INITRANS 1
MAXTRANS 255
NOCOMPRESS
LOGGING
STORAGE (INITIAL 65536
         NEXT 1048576
         MINEXTENTS 1
         MAXEXTENTS 2147483645
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT
         FLASH_CACHE DEFAULT
         CELL_FLASH_CACHE DEFAULT)
TABLESPACE cwms_20data;

ALTER TABLE CWMS_20.CWMS_COUNTY_SP
 ADD CONSTRAINT CWMS_COUNTY_SP_U1
  UNIQUE (COUNTY,STATE)
  ENABLE VALIDATE;

