CREATE SMALLFILE TABLESPACE "CWMS_20AT_DATA" DATAFILE '/orabase/oradata/wq0xe/cwms_at_data_01' SIZE 200M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
CREATE SMALLFILE TABLESPACE "CWMS_20DATA" DATAFILE '/orabase/oradata/wq0xe/cwms_data_01' SIZE 500M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
CREATE SMALLFILE TABLESPACE "CWMS_20_TSV" DATAFILE '/orabase/oradata/wq0xe/cwms_tsv_01' SIZE 500M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/