CREATE SMALLFILE TABLESPACE "CWMS_20AT_DATA" DATAFILE 'C:\ORACLE\ORADATA\CWMSDEV\CWMS_DEV_at_data_01' SIZE 200M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
CREATE SMALLFILE TABLESPACE "CWMS_20DATA" DATAFILE 'C:\ORACLE\ORADATA\CWMSDEV\CWMS_DEV_data_01' SIZE 500M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
CREATE SMALLFILE TABLESPACE "CWMS_20_TSV" DATAFILE 'C:\ORACLE\ORADATA\CWMSDEV\CWMS_DEV_tsv_01' SIZE 500M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO 
/
CREATE SMALLFILE TABLESPACE "CWMS_AQ" DATAFILE 'C:\ORACLE\ORADATA\CWMSDEV\CWMS_DEV_AQ_01' SIZE 500M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/
CREATE SMALLFILE TABLESPACE "CWMS_AQ_EX" DATAFILE 'C:\ORACLE\ORADATA\CWMSDEV\CWMS_DEV_AQ_EX_01' SIZE 500M REUSE LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO
/
