-- Run as the schema owner from schema/src/updateScripts, before deploying
-- an API that writes time series display preferences. Requires current main.
-- Use a prepared schema source tree with cwms/defines.sql generated by autobuild.py.
whenever sqlerror exit failure rollback
set define on
set verify off
set serveroutput on
define cwms_schema = CWMS_20
define builduser = CWMS_20
alter session set current_schema = &&cwms_schema;
spool update_issue_223-ts_display_units.log

@@../cwms/tables/at_ts_display_units.sql
@@../cwms/cwms_ts_pkg.sql
@@../cwms/cwms_ts_pkg_body.sql
delete from at_clob where id = '/VIEWDOCS/AV_TS_GRP_ASSGN' and office_code = 53;
@@../cwms/views/av_ts_grp_assgn.sql
@@../cwms/cwms_schema_pkg.sql

begin
   dbms_rls.add_policy(
      object_schema => '&&cwms_schema',
      object_name => 'AT_TS_DISPLAY_UNITS',
      policy_name => 'SERVICE_USER_POLICY',
      function_schema => '&&cwms_schema',
      policy_function => 'CWMS_SEC_POLICY.CHECK_SESSION_USER',
      policy_type => dbms_rls.shared_context_sensitive,
      statement_types => 'select');
   dbms_utility.compile_schema('&&cwms_schema', compile_all => false);
end;
/

declare
   l_errors integer;
begin
   select count(*) into l_errors from user_errors
    where name in ('CWMS_TS', 'CWMS_SCHEMA', 'AV_TS_GRP_ASSGN', 'ST_TS_DISPLAY_UNITS')
      and attribute = 'ERROR';
   if l_errors > 0 then
      raise_application_error(-20000, 'Issue 223 installation has compilation errors; inspect USER_ERRORS');
   end if;
end;
/
commit;
spool off
