CREATE TABLE CWMS_20.AT_TSV_2021
(
  TS_CODE          NUMBER(14)                   NOT NULL,
  DATE_TIME        DATE                         NOT NULL,
  VERSION_DATE     DATE                         NOT NULL,
  DATA_ENTRY_DATE  TIMESTAMP(6)                 NOT NULL,
  VALUE            BINARY_DOUBLE,
  QUALITY_CODE     NUMBER(14),
  DEST_FLAG        NUMBER(1), 
  CONSTRAINT AT_TSV_2021_PK
  PRIMARY KEY
  (TS_CODE, DATE_TIME, VERSION_DATE)
  ENABLE VALIDATE
)
ORGANIZATION INDEX
PCTTHRESHOLD 50
TABLESPACE CWMS_20_TSV
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
COMPRESS 2
NOPARALLEL
MONITORING;
