--
-- AT_DATA_STREAM_PROPERTIES  (Table) 
--
--  Dependencies: 
--   CWMS_OFFICE (Table)
--
CREATE TABLE AT_DATA_STREAM_PROPERTIES
(
  DB_OFFICE_CODE      NUMBER,
  UPDATE_IDLE_PERIOD  NUMBER,
  UPDATE_TIME         VARCHAR2(32 BYTE)
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- AT_DATA_STREAM_PROPERTIES_PK  (Index) 
--
--  Dependencies: 
--   AT_DATA_STREAM_PROPERTIES (Table)
--
CREATE UNIQUE INDEX AT_DATA_STREAM_PROPERTIES_PK ON AT_DATA_STREAM_PROPERTIES
(DB_OFFICE_CODE)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table AT_DATA_STREAM_PROPERTIES 
-- 
ALTER TABLE AT_DATA_STREAM_PROPERTIES ADD (
  CONSTRAINT AT_DATA_STREAM_PROPERTIES_PK
  PRIMARY KEY
  (DB_OFFICE_CODE)
  USING INDEX AT_DATA_STREAM_PROPERTIES_PK)
/

-- 
-- Foreign Key Constraints for Table AT_DATA_STREAM_PROPERTIES 
-- 
ALTER TABLE AT_DATA_STREAM_PROPERTIES ADD (
  CONSTRAINT AT_DATA_STREAM_PROPERTIES_R01 
  FOREIGN KEY (DB_OFFICE_CODE) 
  REFERENCES CWMS_OFFICE (OFFICE_CODE))
/
