--
-- AT_SHEF_CRIT_FILE_REC  (Table) 
--
--  Dependencies: 
--   AT_DATA_STREAM_ID (Table)
--
CREATE TABLE AT_SHEF_CRIT_FILE_REC
(
  CRIT_FILE_CODE           NUMBER,
  DATA_STREAM_CODE         NUMBER,
  CRIT_FILE_CREATION_DATE  DATE,
  NUM_DECODE_PROCESS_RECS  NUMBER,
  NUM_DECODE_IGNORE_RECS   NUMBER,
  NUM_IGNORE_RECS          NUMBER,
  CRIT_FILE_HASH           NUMBER
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


--
-- AT_SHEF_CRIT_FILE_REC_PK  (Index) 
--
--  Dependencies: 
--   AT_SHEF_CRIT_FILE_REC (Table)
--
CREATE UNIQUE INDEX AT_SHEF_CRIT_FILE_REC_PK ON AT_SHEF_CRIT_FILE_REC
(CRIT_FILE_CODE)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


--
-- AT_SHEF_CRIT_FILE_REC_U01  (Index) 
--
--  Dependencies: 
--   AT_SHEF_CRIT_FILE_REC (Table)
--
CREATE UNIQUE INDEX AT_SHEF_CRIT_FILE_REC_U01 ON AT_SHEF_CRIT_FILE_REC
(DATA_STREAM_CODE, CRIT_FILE_CREATION_DATE)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL
/


-- 
-- Non Foreign Key Constraints for Table AT_SHEF_CRIT_FILE_REC 
-- 
ALTER TABLE AT_SHEF_CRIT_FILE_REC ADD (
  CONSTRAINT AT_SHEF_CRIT_FILE_REC_PK
  PRIMARY KEY
  (CRIT_FILE_CODE)
  USING INDEX AT_SHEF_CRIT_FILE_REC_PK,
  CONSTRAINT AT_SHEF_CRIT_FILE_REC_U01
  UNIQUE (DATA_STREAM_CODE, CRIT_FILE_CREATION_DATE)
  USING INDEX AT_SHEF_CRIT_FILE_REC_U01)
/

-- 
-- Foreign Key Constraints for Table AT_SHEF_CRIT_FILE_REC 
-- 
ALTER TABLE AT_SHEF_CRIT_FILE_REC ADD (
  CONSTRAINT AT_SHEF_CRIT_FILE_REC_R01 
  FOREIGN KEY (DATA_STREAM_CODE) 
  REFERENCES AT_DATA_STREAM_ID (DATA_STREAM_CODE))
/
