CREATE TABLE AT_SHEF_DECODE_SPEC
(
  CRIT_FILE_CODE         NUMBER,
  TS_CODE                NUMBER,
  CWMS_TS_ID             VARCHAR2(183 BYTE),
  DB_OFFICE_ID           VARCHAR2(16 BYTE),
  DATA_STREAM_ID         VARCHAR2(16 BYTE),
  STREAM_DB_OFFICE_ID    VARCHAR2(16 BYTE),
  DATA_FEED_ID           VARCHAR2(32 BYTE),
  FEED_DB_OFFICE_ID      VARCHAR2(16 BYTE),
  DATA_FEED_PREFIX       VARCHAR2(3 BYTE),
  LOC_GROUP_ID           VARCHAR2(65 BYTE),
  LOC_CATEGORY_ID        VARCHAR2(32 BYTE),
  LOC_ALIAS_ID           VARCHAR2(256 BYTE),
  SHEF_LOC_ID            VARCHAR2(128 BYTE),
  SHEF_PE_CODE           VARCHAR2(2 BYTE),
  SHEF_TSE_CODE          VARCHAR2(3 BYTE),
  SHEF_DURATION_CODE     VARCHAR2(1 BYTE),
  SHEF_DURATION_NUMERIC  VARCHAR2(4 BYTE),
  SHEF_TIME_ZONE_ID      VARCHAR2(16 BYTE),
  DL_TIME                VARCHAR2(1 BYTE),
  UNIT_ID                VARCHAR2(16 BYTE),
  UNIT_SYSTEM            VARCHAR2(2 BYTE),
  INTERVAL_UTC_OFFSET    NUMBER,
  INTERVAL_FORWARD       NUMBER,
  INTERVAL_BACKWARD      NUMBER,
  TS_ACTIVE_FLAG         VARCHAR2(1 BYTE),
  NET_TS_ACTIVE_FLAG     CHAR(1 BYTE),
  IGNORE_SHEF_SPEC       VARCHAR2(1 BYTE),
  SHEF_SPEC              VARCHAR2(271 BYTE),
  LOCATION_ID            VARCHAR2(57 BYTE),
  PARAMETER_ID           VARCHAR2(49 BYTE),
  PARAMETER_TYPE_ID      VARCHAR2(16 BYTE),
  INTERVAL_ID            VARCHAR2(16 BYTE),
  DURATION_ID            VARCHAR2(16 BYTE),
  VERSION_ID             VARCHAR2(32 BYTE),
  DATA_STREAM_CODE       NUMBER,
  SHEF_CRIT_LINE         VARCHAR2(2000 BYTE)
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


CREATE INDEX AT_SHEF_DECODE_SPEC_NU01 ON AT_SHEF_DECODE_SPEC
(CRIT_FILE_CODE)
LOGGING
TABLESPACE CWMS_20AT_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL
/
