---
name: Build And Test CWMS Database
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: setup java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Oracle Tools
        id: cache-oracle-tools
        uses: actions/cache@v4.2.0
        with:
          path: oracle-tools
          key: oracle-tools
      - name: Download Oracle Tools
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          echo "Hello" > /oracle-tools/hello.txt
          echo "I ran."
      - name: Test download
        run: cat /oracle-tools/hello.txt