whenever sqlerror continue;
alter table at_physical_location add search_doc varchar2(1000);    
comment on column at_physical_location.search_doc is 'Placeholder column for Oracle Text full-text search index. The indexed document text is dynamically generated by the USER_DATASTORE procedure (CWMS_LOC.BUILD_SEARCH_DOC) during indexing and is not stored in this column.';
@@../cwms/oracle_test/setup_indexes
delete from at_clob where id in ('/VIEWDOCS/AV_LOC', '/VIEWDOCS/AV_LOC2');
@@../cwms/views/av_loc
@@../cwms/views/av_loc2
@@../cwms/cwms_loc_pkg
@@../cwms/cwms_loc_pkg_body
whenever sqlerror exit;
