CREATE TABLE AT_USER_LISTS
(
  DB_OFFICE_CODE     NUMBER         NOT NULL,
  USER_LIST_ID       VARCHAR2(128)  NOT NULL,
  USER_LIST_DESC     VARCHAR2(1024),
  OWNED_BY_USERID    VARCHAR2(128),
  CREATED_AT         TIMESTAMP      DEFAULT current_timestamp NOT NULL,
  UPDATED_AT         TIMESTAMP
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE AT_USER_LISTS IS 'User-defined lists of CWMS users with an owning office'
/

CREATE UNIQUE INDEX AT_USER_LISTS_PK ON AT_USER_LISTS
(USER_LIST_ID)
LOGGING
TABLESPACE CWMS_20AT_DATA
/

ALTER TABLE AT_USER_LISTS ADD (
  CONSTRAINT AT_USER_LISTS_PK
  PRIMARY KEY
  (USER_LIST_ID)
  USING INDEX AT_USER_LISTS_PK)
/

ALTER TABLE AT_USER_LISTS ADD (
  CONSTRAINT AT_USER_LISTS_FK1
  FOREIGN KEY (DB_OFFICE_CODE)
  REFERENCES CWMS_OFFICE (OFFICE_CODE),
  CONSTRAINT AT_USER_LISTS_FK2
  FOREIGN KEY (OWNED_BY_USERID)
  REFERENCES AT_SEC_CWMS_USERS (USERID),
  CONSTRAINT AT_USER_LISTS_CK1
  CHECK (USER_LIST_ID = UPPER(USER_LIST_ID)),
  CONSTRAINT AT_USER_LISTS_CK2
  CHECK (OWNED_BY_USERID = UPPER(OWNED_BY_USERID)))
/

CREATE OR REPLACE TRIGGER AT_USER_LISTS_TRIG
        BEFORE INSERT OR UPDATE
        ON AT_USER_LISTS
        REFERENCING NEW AS new OLD AS old
        FOR EACH ROW
DECLARE
BEGIN
        :new.user_list_id := UPPER (:new.user_list_id);
        :new.owned_by_userid := UPPER (:new.owned_by_userid);
        :new.updated_at := current_timestamp;
END;
/

CREATE OR REPLACE TRIGGER ST_USER_LISTS BEFORE DELETE OR INSERT OR UPDATE
              ON AT_USER_LISTS REFERENCING NEW AS NEW OLD AS OLD

             DECLARE

             l_priv   VARCHAR2 (16);
             BEGIN
             l_priv := NVL(SYS_CONTEXT ('CWMS_ENV', 'CWMS_PRIVILEGE'),'');
             IF (l_priv <> 'CAN_WRITE' AND user NOT IN ('SYS', 'CWMS_20', upper('builduser')))
             THEN

               CWMS_20.CWMS_ERR.RAISE('NO_WRITE_PRIVILEGE');

             END IF;
           END;
/

CREATE TABLE AT_USER_LIST_MEMBERS
(
  USER_LIST_ID      VARCHAR2(128)  NOT NULL,
  USERID            VARCHAR2(128)  NOT NULL,
  ADD_DATE          TIMESTAMP      DEFAULT current_timestamp NOT NULL,
  ADDED_BY_USERID   VARCHAR2(128)
)
TABLESPACE CWMS_20AT_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
/

COMMENT ON TABLE AT_USER_LIST_MEMBERS IS 'Membership rows linking CWMS users to user-defined lists'
/

CREATE UNIQUE INDEX AT_USER_LIST_MEMBERS_PK ON AT_USER_LIST_MEMBERS
(USER_LIST_ID, USERID)
LOGGING
TABLESPACE CWMS_20AT_DATA
/

ALTER TABLE AT_USER_LIST_MEMBERS ADD (
  CONSTRAINT AT_USER_LIST_MEMBERS_PK
  PRIMARY KEY
  (USER_LIST_ID, USERID)
  USING INDEX AT_USER_LIST_MEMBERS_PK)
/

ALTER TABLE AT_USER_LIST_MEMBERS ADD (
  CONSTRAINT AT_USER_LIST_MEMBERS_FK1
  FOREIGN KEY (USER_LIST_ID)
  REFERENCES AT_USER_LISTS (USER_LIST_ID),
  CONSTRAINT AT_USER_LIST_MEMBERS_FK2
  FOREIGN KEY (USERID)
  REFERENCES AT_SEC_CWMS_USERS (USERID),
  CONSTRAINT AT_USER_LIST_MEMBERS_FK3
  FOREIGN KEY (ADDED_BY_USERID)
  REFERENCES AT_SEC_CWMS_USERS (USERID),
  CONSTRAINT AT_USER_LIST_MEMBERS_CK1
  CHECK (USER_LIST_ID = UPPER(USER_LIST_ID)),
  CONSTRAINT AT_USER_LIST_MEMBERS_CK2
  CHECK (USERID = UPPER(USERID)),
  CONSTRAINT AT_USER_LIST_MEMBERS_CK3
  CHECK (ADDED_BY_USERID = UPPER(ADDED_BY_USERID)))
/

CREATE OR REPLACE TRIGGER ST_USER_LIST_MEMBERS BEFORE DELETE OR INSERT OR UPDATE
              ON AT_USER_LIST_MEMBERS REFERENCING NEW AS NEW OLD AS OLD

             DECLARE

             l_priv   VARCHAR2 (16);
             BEGIN
             l_priv := NVL(SYS_CONTEXT ('CWMS_ENV', 'CWMS_PRIVILEGE'),'');
             IF (l_priv <> 'CAN_WRITE' AND user NOT IN ('SYS', 'CWMS_20', upper('builduser')))
             THEN

               CWMS_20.CWMS_ERR.RAISE('NO_WRITE_PRIVILEGE');

             END IF;
           END;
/
@@../cwms/views/av_user_list_members
create or replace public synonym cwms_v_user_list_members for av_user_list_members;